import "../../../just/settings.just"

COMPONENT_DIR := module_directory()
ROOT_DIR := clean(join(COMPONENT_DIR, "../../.."))
PNPM := env("PNPM", "pnpm")
WEB_PACKAGE := "@plateau/iam-web"

[unix]
[working-directory(ROOT_DIR)]
dev *args:
    @"{{ PNPM }}" --filter "{{ WEB_PACKAGE }}" run dev {{ args }}

[windows]
[working-directory(ROOT_DIR)]
dev *args:
    @& "{{ PNPM }}" --filter "{{ WEB_PACKAGE }}" run dev {{ args }}

[unix]
[working-directory(ROOT_DIR)]
build:
    @"{{ PNPM }}" --filter "{{ WEB_PACKAGE }}" run build

[windows]
[working-directory(ROOT_DIR)]
build:
    @& "{{ PNPM }}" --filter "{{ WEB_PACKAGE }}" run build

[unix]
[working-directory(ROOT_DIR)]
lint:
    @"{{ PNPM }}" --filter "{{ WEB_PACKAGE }}" run lint

[windows]
[working-directory(ROOT_DIR)]
lint:
    @& "{{ PNPM }}" --filter "{{ WEB_PACKAGE }}" run lint
