// Code generated by ent, DO NOT EDIT.

package emailverificationtoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldUserID, v))
}

// LoginIdentifierID applies equality check predicate on the "login_identifier_id" field. It's identical to LoginIdentifierIDEQ.
func LoginIdentifierID(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldLoginIdentifierID, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldTokenHash, v))
}

// ExpiresTime applies equality check predicate on the "expires_time" field. It's identical to ExpiresTimeEQ.
func ExpiresTime(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldExpiresTime, v))
}

// ConsumedTime applies equality check predicate on the "consumed_time" field. It's identical to ConsumedTimeEQ.
func ConsumedTime(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldConsumedTime, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldCreateTime, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldContainsFold(FieldUserID, v))
}

// LoginIdentifierIDEQ applies the EQ predicate on the "login_identifier_id" field.
func LoginIdentifierIDEQ(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldLoginIdentifierID, v))
}

// LoginIdentifierIDNEQ applies the NEQ predicate on the "login_identifier_id" field.
func LoginIdentifierIDNEQ(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNEQ(FieldLoginIdentifierID, v))
}

// LoginIdentifierIDIn applies the In predicate on the "login_identifier_id" field.
func LoginIdentifierIDIn(vs ...string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldIn(FieldLoginIdentifierID, vs...))
}

// LoginIdentifierIDNotIn applies the NotIn predicate on the "login_identifier_id" field.
func LoginIdentifierIDNotIn(vs ...string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNotIn(FieldLoginIdentifierID, vs...))
}

// LoginIdentifierIDGT applies the GT predicate on the "login_identifier_id" field.
func LoginIdentifierIDGT(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGT(FieldLoginIdentifierID, v))
}

// LoginIdentifierIDGTE applies the GTE predicate on the "login_identifier_id" field.
func LoginIdentifierIDGTE(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGTE(FieldLoginIdentifierID, v))
}

// LoginIdentifierIDLT applies the LT predicate on the "login_identifier_id" field.
func LoginIdentifierIDLT(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLT(FieldLoginIdentifierID, v))
}

// LoginIdentifierIDLTE applies the LTE predicate on the "login_identifier_id" field.
func LoginIdentifierIDLTE(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLTE(FieldLoginIdentifierID, v))
}

// LoginIdentifierIDContains applies the Contains predicate on the "login_identifier_id" field.
func LoginIdentifierIDContains(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldContains(FieldLoginIdentifierID, v))
}

// LoginIdentifierIDHasPrefix applies the HasPrefix predicate on the "login_identifier_id" field.
func LoginIdentifierIDHasPrefix(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldHasPrefix(FieldLoginIdentifierID, v))
}

// LoginIdentifierIDHasSuffix applies the HasSuffix predicate on the "login_identifier_id" field.
func LoginIdentifierIDHasSuffix(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldHasSuffix(FieldLoginIdentifierID, v))
}

// LoginIdentifierIDEqualFold applies the EqualFold predicate on the "login_identifier_id" field.
func LoginIdentifierIDEqualFold(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEqualFold(FieldLoginIdentifierID, v))
}

// LoginIdentifierIDContainsFold applies the ContainsFold predicate on the "login_identifier_id" field.
func LoginIdentifierIDContainsFold(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldContainsFold(FieldLoginIdentifierID, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldContainsFold(FieldTokenHash, v))
}

// ExpiresTimeEQ applies the EQ predicate on the "expires_time" field.
func ExpiresTimeEQ(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldExpiresTime, v))
}

// ExpiresTimeNEQ applies the NEQ predicate on the "expires_time" field.
func ExpiresTimeNEQ(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNEQ(FieldExpiresTime, v))
}

// ExpiresTimeIn applies the In predicate on the "expires_time" field.
func ExpiresTimeIn(vs ...time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldIn(FieldExpiresTime, vs...))
}

// ExpiresTimeNotIn applies the NotIn predicate on the "expires_time" field.
func ExpiresTimeNotIn(vs ...time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNotIn(FieldExpiresTime, vs...))
}

// ExpiresTimeGT applies the GT predicate on the "expires_time" field.
func ExpiresTimeGT(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGT(FieldExpiresTime, v))
}

// ExpiresTimeGTE applies the GTE predicate on the "expires_time" field.
func ExpiresTimeGTE(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGTE(FieldExpiresTime, v))
}

// ExpiresTimeLT applies the LT predicate on the "expires_time" field.
func ExpiresTimeLT(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLT(FieldExpiresTime, v))
}

// ExpiresTimeLTE applies the LTE predicate on the "expires_time" field.
func ExpiresTimeLTE(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLTE(FieldExpiresTime, v))
}

// ConsumedTimeEQ applies the EQ predicate on the "consumed_time" field.
func ConsumedTimeEQ(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldConsumedTime, v))
}

// ConsumedTimeNEQ applies the NEQ predicate on the "consumed_time" field.
func ConsumedTimeNEQ(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNEQ(FieldConsumedTime, v))
}

// ConsumedTimeIn applies the In predicate on the "consumed_time" field.
func ConsumedTimeIn(vs ...time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldIn(FieldConsumedTime, vs...))
}

// ConsumedTimeNotIn applies the NotIn predicate on the "consumed_time" field.
func ConsumedTimeNotIn(vs ...time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNotIn(FieldConsumedTime, vs...))
}

// ConsumedTimeGT applies the GT predicate on the "consumed_time" field.
func ConsumedTimeGT(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGT(FieldConsumedTime, v))
}

// ConsumedTimeGTE applies the GTE predicate on the "consumed_time" field.
func ConsumedTimeGTE(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGTE(FieldConsumedTime, v))
}

// ConsumedTimeLT applies the LT predicate on the "consumed_time" field.
func ConsumedTimeLT(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLT(FieldConsumedTime, v))
}

// ConsumedTimeLTE applies the LTE predicate on the "consumed_time" field.
func ConsumedTimeLTE(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLTE(FieldConsumedTime, v))
}

// ConsumedTimeIsNil applies the IsNil predicate on the "consumed_time" field.
func ConsumedTimeIsNil() predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldIsNull(FieldConsumedTime))
}

// ConsumedTimeNotNil applies the NotNil predicate on the "consumed_time" field.
func ConsumedTimeNotNil() predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNotNull(FieldConsumedTime))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.FieldLTE(FieldCreateTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmailVerificationToken) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmailVerificationToken) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmailVerificationToken) predicate.EmailVerificationToken {
	return predicate.EmailVerificationToken(sql.NotPredicates(p))
}
