// Code generated by ent, DO NOT EDIT.

package loginidentifier

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldUserID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldType, v))
}

// CanonicalValue applies equality check predicate on the "canonical_value" field. It's identical to CanonicalValueEQ.
func CanonicalValue(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldCanonicalValue, v))
}

// DisplayValue applies equality check predicate on the "display_value" field. It's identical to DisplayValueEQ.
func DisplayValue(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldDisplayValue, v))
}

// VerifiedTime applies equality check predicate on the "verified_time" field. It's identical to VerifiedTimeEQ.
func VerifiedTime(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldVerifiedTime, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldUpdateTime, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldContainsFold(FieldUserID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldContainsFold(FieldType, v))
}

// CanonicalValueEQ applies the EQ predicate on the "canonical_value" field.
func CanonicalValueEQ(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldCanonicalValue, v))
}

// CanonicalValueNEQ applies the NEQ predicate on the "canonical_value" field.
func CanonicalValueNEQ(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNEQ(FieldCanonicalValue, v))
}

// CanonicalValueIn applies the In predicate on the "canonical_value" field.
func CanonicalValueIn(vs ...string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldIn(FieldCanonicalValue, vs...))
}

// CanonicalValueNotIn applies the NotIn predicate on the "canonical_value" field.
func CanonicalValueNotIn(vs ...string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNotIn(FieldCanonicalValue, vs...))
}

// CanonicalValueGT applies the GT predicate on the "canonical_value" field.
func CanonicalValueGT(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGT(FieldCanonicalValue, v))
}

// CanonicalValueGTE applies the GTE predicate on the "canonical_value" field.
func CanonicalValueGTE(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGTE(FieldCanonicalValue, v))
}

// CanonicalValueLT applies the LT predicate on the "canonical_value" field.
func CanonicalValueLT(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLT(FieldCanonicalValue, v))
}

// CanonicalValueLTE applies the LTE predicate on the "canonical_value" field.
func CanonicalValueLTE(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLTE(FieldCanonicalValue, v))
}

// CanonicalValueContains applies the Contains predicate on the "canonical_value" field.
func CanonicalValueContains(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldContains(FieldCanonicalValue, v))
}

// CanonicalValueHasPrefix applies the HasPrefix predicate on the "canonical_value" field.
func CanonicalValueHasPrefix(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldHasPrefix(FieldCanonicalValue, v))
}

// CanonicalValueHasSuffix applies the HasSuffix predicate on the "canonical_value" field.
func CanonicalValueHasSuffix(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldHasSuffix(FieldCanonicalValue, v))
}

// CanonicalValueEqualFold applies the EqualFold predicate on the "canonical_value" field.
func CanonicalValueEqualFold(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEqualFold(FieldCanonicalValue, v))
}

// CanonicalValueContainsFold applies the ContainsFold predicate on the "canonical_value" field.
func CanonicalValueContainsFold(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldContainsFold(FieldCanonicalValue, v))
}

// DisplayValueEQ applies the EQ predicate on the "display_value" field.
func DisplayValueEQ(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldDisplayValue, v))
}

// DisplayValueNEQ applies the NEQ predicate on the "display_value" field.
func DisplayValueNEQ(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNEQ(FieldDisplayValue, v))
}

// DisplayValueIn applies the In predicate on the "display_value" field.
func DisplayValueIn(vs ...string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldIn(FieldDisplayValue, vs...))
}

// DisplayValueNotIn applies the NotIn predicate on the "display_value" field.
func DisplayValueNotIn(vs ...string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNotIn(FieldDisplayValue, vs...))
}

// DisplayValueGT applies the GT predicate on the "display_value" field.
func DisplayValueGT(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGT(FieldDisplayValue, v))
}

// DisplayValueGTE applies the GTE predicate on the "display_value" field.
func DisplayValueGTE(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGTE(FieldDisplayValue, v))
}

// DisplayValueLT applies the LT predicate on the "display_value" field.
func DisplayValueLT(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLT(FieldDisplayValue, v))
}

// DisplayValueLTE applies the LTE predicate on the "display_value" field.
func DisplayValueLTE(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLTE(FieldDisplayValue, v))
}

// DisplayValueContains applies the Contains predicate on the "display_value" field.
func DisplayValueContains(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldContains(FieldDisplayValue, v))
}

// DisplayValueHasPrefix applies the HasPrefix predicate on the "display_value" field.
func DisplayValueHasPrefix(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldHasPrefix(FieldDisplayValue, v))
}

// DisplayValueHasSuffix applies the HasSuffix predicate on the "display_value" field.
func DisplayValueHasSuffix(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldHasSuffix(FieldDisplayValue, v))
}

// DisplayValueEqualFold applies the EqualFold predicate on the "display_value" field.
func DisplayValueEqualFold(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEqualFold(FieldDisplayValue, v))
}

// DisplayValueContainsFold applies the ContainsFold predicate on the "display_value" field.
func DisplayValueContainsFold(v string) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldContainsFold(FieldDisplayValue, v))
}

// VerifiedTimeEQ applies the EQ predicate on the "verified_time" field.
func VerifiedTimeEQ(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldVerifiedTime, v))
}

// VerifiedTimeNEQ applies the NEQ predicate on the "verified_time" field.
func VerifiedTimeNEQ(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNEQ(FieldVerifiedTime, v))
}

// VerifiedTimeIn applies the In predicate on the "verified_time" field.
func VerifiedTimeIn(vs ...time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldIn(FieldVerifiedTime, vs...))
}

// VerifiedTimeNotIn applies the NotIn predicate on the "verified_time" field.
func VerifiedTimeNotIn(vs ...time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNotIn(FieldVerifiedTime, vs...))
}

// VerifiedTimeGT applies the GT predicate on the "verified_time" field.
func VerifiedTimeGT(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGT(FieldVerifiedTime, v))
}

// VerifiedTimeGTE applies the GTE predicate on the "verified_time" field.
func VerifiedTimeGTE(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGTE(FieldVerifiedTime, v))
}

// VerifiedTimeLT applies the LT predicate on the "verified_time" field.
func VerifiedTimeLT(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLT(FieldVerifiedTime, v))
}

// VerifiedTimeLTE applies the LTE predicate on the "verified_time" field.
func VerifiedTimeLTE(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLTE(FieldVerifiedTime, v))
}

// VerifiedTimeIsNil applies the IsNil predicate on the "verified_time" field.
func VerifiedTimeIsNil() predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldIsNull(FieldVerifiedTime))
}

// VerifiedTimeNotNil applies the NotNil predicate on the "verified_time" field.
func VerifiedTimeNotNil() predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNotNull(FieldVerifiedTime))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.FieldLTE(FieldUpdateTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LoginIdentifier) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LoginIdentifier) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LoginIdentifier) predicate.LoginIdentifier {
	return predicate.LoginIdentifier(sql.NotPredicates(p))
}
