// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/authenticator"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/predicate"
)

// AuthenticatorUpdate is the builder for updating Authenticator entities.
type AuthenticatorUpdate struct {
	config
	hooks     []Hook
	mutation  *AuthenticatorMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AuthenticatorUpdate builder.
func (_u *AuthenticatorUpdate) Where(ps ...predicate.Authenticator) *AuthenticatorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetState sets the "state" field.
func (_u *AuthenticatorUpdate) SetState(v string) *AuthenticatorUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *AuthenticatorUpdate) SetNillableState(v *string) *AuthenticatorUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *AuthenticatorUpdate) SetDisplayName(v string) *AuthenticatorUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *AuthenticatorUpdate) SetNillableDisplayName(v *string) *AuthenticatorUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *AuthenticatorUpdate) ClearDisplayName() *AuthenticatorUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetVerifiedTime sets the "verified_time" field.
func (_u *AuthenticatorUpdate) SetVerifiedTime(v time.Time) *AuthenticatorUpdate {
	_u.mutation.SetVerifiedTime(v)
	return _u
}

// SetNillableVerifiedTime sets the "verified_time" field if the given value is not nil.
func (_u *AuthenticatorUpdate) SetNillableVerifiedTime(v *time.Time) *AuthenticatorUpdate {
	if v != nil {
		_u.SetVerifiedTime(*v)
	}
	return _u
}

// ClearVerifiedTime clears the value of the "verified_time" field.
func (_u *AuthenticatorUpdate) ClearVerifiedTime() *AuthenticatorUpdate {
	_u.mutation.ClearVerifiedTime()
	return _u
}

// SetLastUsedTime sets the "last_used_time" field.
func (_u *AuthenticatorUpdate) SetLastUsedTime(v time.Time) *AuthenticatorUpdate {
	_u.mutation.SetLastUsedTime(v)
	return _u
}

// SetNillableLastUsedTime sets the "last_used_time" field if the given value is not nil.
func (_u *AuthenticatorUpdate) SetNillableLastUsedTime(v *time.Time) *AuthenticatorUpdate {
	if v != nil {
		_u.SetLastUsedTime(*v)
	}
	return _u
}

// ClearLastUsedTime clears the value of the "last_used_time" field.
func (_u *AuthenticatorUpdate) ClearLastUsedTime() *AuthenticatorUpdate {
	_u.mutation.ClearLastUsedTime()
	return _u
}

// SetRevokedTime sets the "revoked_time" field.
func (_u *AuthenticatorUpdate) SetRevokedTime(v time.Time) *AuthenticatorUpdate {
	_u.mutation.SetRevokedTime(v)
	return _u
}

// SetNillableRevokedTime sets the "revoked_time" field if the given value is not nil.
func (_u *AuthenticatorUpdate) SetNillableRevokedTime(v *time.Time) *AuthenticatorUpdate {
	if v != nil {
		_u.SetRevokedTime(*v)
	}
	return _u
}

// ClearRevokedTime clears the value of the "revoked_time" field.
func (_u *AuthenticatorUpdate) ClearRevokedTime() *AuthenticatorUpdate {
	_u.mutation.ClearRevokedTime()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *AuthenticatorUpdate) SetUpdateTime(v time.Time) *AuthenticatorUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the AuthenticatorMutation object of the builder.
func (_u *AuthenticatorUpdate) Mutation() *AuthenticatorMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthenticatorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthenticatorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthenticatorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthenticatorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthenticatorUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := authenticator.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AuthenticatorUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AuthenticatorUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AuthenticatorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(authenticator.Table, authenticator.Columns, sqlgraph.NewFieldSpec(authenticator.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(authenticator.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(authenticator.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(authenticator.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.VerifiedTime(); ok {
		_spec.SetField(authenticator.FieldVerifiedTime, field.TypeTime, value)
	}
	if _u.mutation.VerifiedTimeCleared() {
		_spec.ClearField(authenticator.FieldVerifiedTime, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedTime(); ok {
		_spec.SetField(authenticator.FieldLastUsedTime, field.TypeTime, value)
	}
	if _u.mutation.LastUsedTimeCleared() {
		_spec.ClearField(authenticator.FieldLastUsedTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedTime(); ok {
		_spec.SetField(authenticator.FieldRevokedTime, field.TypeTime, value)
	}
	if _u.mutation.RevokedTimeCleared() {
		_spec.ClearField(authenticator.FieldRevokedTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(authenticator.FieldUpdateTime, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authenticator.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthenticatorUpdateOne is the builder for updating a single Authenticator entity.
type AuthenticatorUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AuthenticatorMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetState sets the "state" field.
func (_u *AuthenticatorUpdateOne) SetState(v string) *AuthenticatorUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *AuthenticatorUpdateOne) SetNillableState(v *string) *AuthenticatorUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *AuthenticatorUpdateOne) SetDisplayName(v string) *AuthenticatorUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *AuthenticatorUpdateOne) SetNillableDisplayName(v *string) *AuthenticatorUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *AuthenticatorUpdateOne) ClearDisplayName() *AuthenticatorUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetVerifiedTime sets the "verified_time" field.
func (_u *AuthenticatorUpdateOne) SetVerifiedTime(v time.Time) *AuthenticatorUpdateOne {
	_u.mutation.SetVerifiedTime(v)
	return _u
}

// SetNillableVerifiedTime sets the "verified_time" field if the given value is not nil.
func (_u *AuthenticatorUpdateOne) SetNillableVerifiedTime(v *time.Time) *AuthenticatorUpdateOne {
	if v != nil {
		_u.SetVerifiedTime(*v)
	}
	return _u
}

// ClearVerifiedTime clears the value of the "verified_time" field.
func (_u *AuthenticatorUpdateOne) ClearVerifiedTime() *AuthenticatorUpdateOne {
	_u.mutation.ClearVerifiedTime()
	return _u
}

// SetLastUsedTime sets the "last_used_time" field.
func (_u *AuthenticatorUpdateOne) SetLastUsedTime(v time.Time) *AuthenticatorUpdateOne {
	_u.mutation.SetLastUsedTime(v)
	return _u
}

// SetNillableLastUsedTime sets the "last_used_time" field if the given value is not nil.
func (_u *AuthenticatorUpdateOne) SetNillableLastUsedTime(v *time.Time) *AuthenticatorUpdateOne {
	if v != nil {
		_u.SetLastUsedTime(*v)
	}
	return _u
}

// ClearLastUsedTime clears the value of the "last_used_time" field.
func (_u *AuthenticatorUpdateOne) ClearLastUsedTime() *AuthenticatorUpdateOne {
	_u.mutation.ClearLastUsedTime()
	return _u
}

// SetRevokedTime sets the "revoked_time" field.
func (_u *AuthenticatorUpdateOne) SetRevokedTime(v time.Time) *AuthenticatorUpdateOne {
	_u.mutation.SetRevokedTime(v)
	return _u
}

// SetNillableRevokedTime sets the "revoked_time" field if the given value is not nil.
func (_u *AuthenticatorUpdateOne) SetNillableRevokedTime(v *time.Time) *AuthenticatorUpdateOne {
	if v != nil {
		_u.SetRevokedTime(*v)
	}
	return _u
}

// ClearRevokedTime clears the value of the "revoked_time" field.
func (_u *AuthenticatorUpdateOne) ClearRevokedTime() *AuthenticatorUpdateOne {
	_u.mutation.ClearRevokedTime()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *AuthenticatorUpdateOne) SetUpdateTime(v time.Time) *AuthenticatorUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// Mutation returns the AuthenticatorMutation object of the builder.
func (_u *AuthenticatorUpdateOne) Mutation() *AuthenticatorMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthenticatorUpdate builder.
func (_u *AuthenticatorUpdateOne) Where(ps ...predicate.Authenticator) *AuthenticatorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthenticatorUpdateOne) Select(field string, fields ...string) *AuthenticatorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Authenticator entity.
func (_u *AuthenticatorUpdateOne) Save(ctx context.Context) (*Authenticator, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthenticatorUpdateOne) SaveX(ctx context.Context) *Authenticator {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthenticatorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthenticatorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthenticatorUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := authenticator.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AuthenticatorUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AuthenticatorUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AuthenticatorUpdateOne) sqlSave(ctx context.Context) (_node *Authenticator, err error) {
	_spec := sqlgraph.NewUpdateSpec(authenticator.Table, authenticator.Columns, sqlgraph.NewFieldSpec(authenticator.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Authenticator.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authenticator.FieldID)
		for _, f := range fields {
			if !authenticator.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authenticator.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(authenticator.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(authenticator.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(authenticator.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.VerifiedTime(); ok {
		_spec.SetField(authenticator.FieldVerifiedTime, field.TypeTime, value)
	}
	if _u.mutation.VerifiedTimeCleared() {
		_spec.ClearField(authenticator.FieldVerifiedTime, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUsedTime(); ok {
		_spec.SetField(authenticator.FieldLastUsedTime, field.TypeTime, value)
	}
	if _u.mutation.LastUsedTimeCleared() {
		_spec.ClearField(authenticator.FieldLastUsedTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedTime(); ok {
		_spec.SetField(authenticator.FieldRevokedTime, field.TypeTime, value)
	}
	if _u.mutation.RevokedTimeCleared() {
		_spec.ClearField(authenticator.FieldRevokedTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(authenticator.FieldUpdateTime, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Authenticator{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authenticator.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
