// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/emailverificationtoken"
)

// EmailVerificationToken is the model entity for the EmailVerificationToken schema.
type EmailVerificationToken struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// LoginIdentifierID holds the value of the "login_identifier_id" field.
	LoginIdentifierID string `json:"login_identifier_id,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"-"`
	// ExpiresTime holds the value of the "expires_time" field.
	ExpiresTime time.Time `json:"expires_time,omitempty"`
	// ConsumedTime holds the value of the "consumed_time" field.
	ConsumedTime *time.Time `json:"consumed_time,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime   time.Time `json:"create_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmailVerificationToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case emailverificationtoken.FieldID, emailverificationtoken.FieldUserID, emailverificationtoken.FieldLoginIdentifierID, emailverificationtoken.FieldTokenHash:
			values[i] = new(sql.NullString)
		case emailverificationtoken.FieldExpiresTime, emailverificationtoken.FieldConsumedTime, emailverificationtoken.FieldCreateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmailVerificationToken fields.
func (_m *EmailVerificationToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case emailverificationtoken.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case emailverificationtoken.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case emailverificationtoken.FieldLoginIdentifierID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field login_identifier_id", values[i])
			} else if value.Valid {
				_m.LoginIdentifierID = value.String
			}
		case emailverificationtoken.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case emailverificationtoken.FieldExpiresTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_time", values[i])
			} else if value.Valid {
				_m.ExpiresTime = value.Time
			}
		case emailverificationtoken.FieldConsumedTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_time", values[i])
			} else if value.Valid {
				_m.ConsumedTime = new(time.Time)
				*_m.ConsumedTime = value.Time
			}
		case emailverificationtoken.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmailVerificationToken.
// This includes values selected through modifiers, order, etc.
func (_m *EmailVerificationToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this EmailVerificationToken.
// Note that you need to call EmailVerificationToken.Unwrap() before calling this method if this EmailVerificationToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EmailVerificationToken) Update() *EmailVerificationTokenUpdateOne {
	return NewEmailVerificationTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EmailVerificationToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EmailVerificationToken) Unwrap() *EmailVerificationToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EmailVerificationToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EmailVerificationToken) String() string {
	var builder strings.Builder
	builder.WriteString("EmailVerificationToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("login_identifier_id=")
	builder.WriteString(_m.LoginIdentifierID)
	builder.WriteString(", ")
	builder.WriteString("token_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("expires_time=")
	builder.WriteString(_m.ExpiresTime.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConsumedTime; v != nil {
		builder.WriteString("consumed_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EmailVerificationTokens is a parsable slice of EmailVerificationToken.
type EmailVerificationTokens []*EmailVerificationToken
