// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/httpsession"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/predicate"
)

// HTTPSessionDelete is the builder for deleting a HTTPSession entity.
type HTTPSessionDelete struct {
	config
	hooks    []Hook
	mutation *HTTPSessionMutation
}

// Where appends a list predicates to the HTTPSessionDelete builder.
func (_d *HTTPSessionDelete) Where(ps ...predicate.HTTPSession) *HTTPSessionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *HTTPSessionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HTTPSessionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *HTTPSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(httpsession.Table, sqlgraph.NewFieldSpec(httpsession.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// HTTPSessionDeleteOne is the builder for deleting a single HTTPSession entity.
type HTTPSessionDeleteOne struct {
	_d *HTTPSessionDelete
}

// Where appends a list predicates to the HTTPSessionDelete builder.
func (_d *HTTPSessionDeleteOne) Where(ps ...predicate.HTTPSession) *HTTPSessionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *HTTPSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{httpsession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HTTPSessionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
