// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/httpsession"
)

// HTTPSessionCreate is the builder for creating a HTTPSession entity.
type HTTPSessionCreate struct {
	config
	mutation *HTTPSessionMutation
	hooks    []Hook
}

// SetData sets the "data" field.
func (_c *HTTPSessionCreate) SetData(v []byte) *HTTPSessionCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetExpiry sets the "expiry" field.
func (_c *HTTPSessionCreate) SetExpiry(v time.Time) *HTTPSessionCreate {
	_c.mutation.SetExpiry(v)
	return _c
}

// SetID sets the "id" field.
func (_c *HTTPSessionCreate) SetID(v string) *HTTPSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the HTTPSessionMutation object of the builder.
func (_c *HTTPSessionCreate) Mutation() *HTTPSessionMutation {
	return _c.mutation
}

// Save creates the HTTPSession in the database.
func (_c *HTTPSessionCreate) Save(ctx context.Context) (*HTTPSession, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HTTPSessionCreate) SaveX(ctx context.Context) *HTTPSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HTTPSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HTTPSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HTTPSessionCreate) check() error {
	if _, ok := _c.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "HTTPSession.data"`)}
	}
	if _, ok := _c.mutation.Expiry(); !ok {
		return &ValidationError{Name: "expiry", err: errors.New(`ent: missing required field "HTTPSession.expiry"`)}
	}
	return nil
}

func (_c *HTTPSessionCreate) sqlSave(ctx context.Context) (*HTTPSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected HTTPSession.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HTTPSessionCreate) createSpec() (*HTTPSession, *sqlgraph.CreateSpec) {
	var (
		_node = &HTTPSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(httpsession.Table, sqlgraph.NewFieldSpec(httpsession.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(httpsession.FieldData, field.TypeBytes, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.Expiry(); ok {
		_spec.SetField(httpsession.FieldExpiry, field.TypeTime, value)
		_node.Expiry = value
	}
	return _node, _spec
}

// HTTPSessionCreateBulk is the builder for creating many HTTPSession entities in bulk.
type HTTPSessionCreateBulk struct {
	config
	err      error
	builders []*HTTPSessionCreate
}

// Save creates the HTTPSession entities in the database.
func (_c *HTTPSessionCreateBulk) Save(ctx context.Context) ([]*HTTPSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HTTPSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HTTPSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HTTPSessionCreateBulk) SaveX(ctx context.Context) []*HTTPSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HTTPSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HTTPSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
