// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/iamloginsession"
)

// IAMLoginSession is the model entity for the IAMLoginSession schema.
type IAMLoginSession struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// SecretHash holds the value of the "secret_hash" field.
	SecretHash string `json:"-"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// LastSeenTime holds the value of the "last_seen_time" field.
	LastSeenTime time.Time `json:"last_seen_time,omitempty"`
	// IdleExpiresTime holds the value of the "idle_expires_time" field.
	IdleExpiresTime time.Time `json:"idle_expires_time,omitempty"`
	// AbsoluteExpiresTime holds the value of the "absolute_expires_time" field.
	AbsoluteExpiresTime time.Time `json:"absolute_expires_time,omitempty"`
	// RevokedTime holds the value of the "revoked_time" field.
	RevokedTime  *time.Time `json:"revoked_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IAMLoginSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case iamloginsession.FieldID, iamloginsession.FieldUserID, iamloginsession.FieldSecretHash:
			values[i] = new(sql.NullString)
		case iamloginsession.FieldCreateTime, iamloginsession.FieldLastSeenTime, iamloginsession.FieldIdleExpiresTime, iamloginsession.FieldAbsoluteExpiresTime, iamloginsession.FieldRevokedTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IAMLoginSession fields.
func (_m *IAMLoginSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case iamloginsession.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case iamloginsession.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case iamloginsession.FieldSecretHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_hash", values[i])
			} else if value.Valid {
				_m.SecretHash = value.String
			}
		case iamloginsession.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case iamloginsession.FieldLastSeenTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_time", values[i])
			} else if value.Valid {
				_m.LastSeenTime = value.Time
			}
		case iamloginsession.FieldIdleExpiresTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field idle_expires_time", values[i])
			} else if value.Valid {
				_m.IdleExpiresTime = value.Time
			}
		case iamloginsession.FieldAbsoluteExpiresTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field absolute_expires_time", values[i])
			} else if value.Valid {
				_m.AbsoluteExpiresTime = value.Time
			}
		case iamloginsession.FieldRevokedTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_time", values[i])
			} else if value.Valid {
				_m.RevokedTime = new(time.Time)
				*_m.RevokedTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IAMLoginSession.
// This includes values selected through modifiers, order, etc.
func (_m *IAMLoginSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IAMLoginSession.
// Note that you need to call IAMLoginSession.Unwrap() before calling this method if this IAMLoginSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IAMLoginSession) Update() *IAMLoginSessionUpdateOne {
	return NewIAMLoginSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IAMLoginSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IAMLoginSession) Unwrap() *IAMLoginSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IAMLoginSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IAMLoginSession) String() string {
	var builder strings.Builder
	builder.WriteString("IAMLoginSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("secret_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_time=")
	builder.WriteString(_m.LastSeenTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("idle_expires_time=")
	builder.WriteString(_m.IdleExpiresTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("absolute_expires_time=")
	builder.WriteString(_m.AbsoluteExpiresTime.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedTime; v != nil {
		builder.WriteString("revoked_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// IAMLoginSessions is a parsable slice of IAMLoginSession.
type IAMLoginSessions []*IAMLoginSession
