// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/iamloginsession"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/predicate"
)

// IAMLoginSessionUpdate is the builder for updating IAMLoginSession entities.
type IAMLoginSessionUpdate struct {
	config
	hooks     []Hook
	mutation  *IAMLoginSessionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the IAMLoginSessionUpdate builder.
func (_u *IAMLoginSessionUpdate) Where(ps ...predicate.IAMLoginSession) *IAMLoginSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSecretHash sets the "secret_hash" field.
func (_u *IAMLoginSessionUpdate) SetSecretHash(v string) *IAMLoginSessionUpdate {
	_u.mutation.SetSecretHash(v)
	return _u
}

// SetNillableSecretHash sets the "secret_hash" field if the given value is not nil.
func (_u *IAMLoginSessionUpdate) SetNillableSecretHash(v *string) *IAMLoginSessionUpdate {
	if v != nil {
		_u.SetSecretHash(*v)
	}
	return _u
}

// SetLastSeenTime sets the "last_seen_time" field.
func (_u *IAMLoginSessionUpdate) SetLastSeenTime(v time.Time) *IAMLoginSessionUpdate {
	_u.mutation.SetLastSeenTime(v)
	return _u
}

// SetNillableLastSeenTime sets the "last_seen_time" field if the given value is not nil.
func (_u *IAMLoginSessionUpdate) SetNillableLastSeenTime(v *time.Time) *IAMLoginSessionUpdate {
	if v != nil {
		_u.SetLastSeenTime(*v)
	}
	return _u
}

// SetIdleExpiresTime sets the "idle_expires_time" field.
func (_u *IAMLoginSessionUpdate) SetIdleExpiresTime(v time.Time) *IAMLoginSessionUpdate {
	_u.mutation.SetIdleExpiresTime(v)
	return _u
}

// SetNillableIdleExpiresTime sets the "idle_expires_time" field if the given value is not nil.
func (_u *IAMLoginSessionUpdate) SetNillableIdleExpiresTime(v *time.Time) *IAMLoginSessionUpdate {
	if v != nil {
		_u.SetIdleExpiresTime(*v)
	}
	return _u
}

// SetRevokedTime sets the "revoked_time" field.
func (_u *IAMLoginSessionUpdate) SetRevokedTime(v time.Time) *IAMLoginSessionUpdate {
	_u.mutation.SetRevokedTime(v)
	return _u
}

// SetNillableRevokedTime sets the "revoked_time" field if the given value is not nil.
func (_u *IAMLoginSessionUpdate) SetNillableRevokedTime(v *time.Time) *IAMLoginSessionUpdate {
	if v != nil {
		_u.SetRevokedTime(*v)
	}
	return _u
}

// ClearRevokedTime clears the value of the "revoked_time" field.
func (_u *IAMLoginSessionUpdate) ClearRevokedTime() *IAMLoginSessionUpdate {
	_u.mutation.ClearRevokedTime()
	return _u
}

// Mutation returns the IAMLoginSessionMutation object of the builder.
func (_u *IAMLoginSessionUpdate) Mutation() *IAMLoginSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IAMLoginSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IAMLoginSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IAMLoginSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IAMLoginSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IAMLoginSessionUpdate) check() error {
	if v, ok := _u.mutation.SecretHash(); ok {
		if err := iamloginsession.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "IAMLoginSession.secret_hash": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *IAMLoginSessionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *IAMLoginSessionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *IAMLoginSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(iamloginsession.Table, iamloginsession.Columns, sqlgraph.NewFieldSpec(iamloginsession.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SecretHash(); ok {
		_spec.SetField(iamloginsession.FieldSecretHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenTime(); ok {
		_spec.SetField(iamloginsession.FieldLastSeenTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IdleExpiresTime(); ok {
		_spec.SetField(iamloginsession.FieldIdleExpiresTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedTime(); ok {
		_spec.SetField(iamloginsession.FieldRevokedTime, field.TypeTime, value)
	}
	if _u.mutation.RevokedTimeCleared() {
		_spec.ClearField(iamloginsession.FieldRevokedTime, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{iamloginsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IAMLoginSessionUpdateOne is the builder for updating a single IAMLoginSession entity.
type IAMLoginSessionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *IAMLoginSessionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetSecretHash sets the "secret_hash" field.
func (_u *IAMLoginSessionUpdateOne) SetSecretHash(v string) *IAMLoginSessionUpdateOne {
	_u.mutation.SetSecretHash(v)
	return _u
}

// SetNillableSecretHash sets the "secret_hash" field if the given value is not nil.
func (_u *IAMLoginSessionUpdateOne) SetNillableSecretHash(v *string) *IAMLoginSessionUpdateOne {
	if v != nil {
		_u.SetSecretHash(*v)
	}
	return _u
}

// SetLastSeenTime sets the "last_seen_time" field.
func (_u *IAMLoginSessionUpdateOne) SetLastSeenTime(v time.Time) *IAMLoginSessionUpdateOne {
	_u.mutation.SetLastSeenTime(v)
	return _u
}

// SetNillableLastSeenTime sets the "last_seen_time" field if the given value is not nil.
func (_u *IAMLoginSessionUpdateOne) SetNillableLastSeenTime(v *time.Time) *IAMLoginSessionUpdateOne {
	if v != nil {
		_u.SetLastSeenTime(*v)
	}
	return _u
}

// SetIdleExpiresTime sets the "idle_expires_time" field.
func (_u *IAMLoginSessionUpdateOne) SetIdleExpiresTime(v time.Time) *IAMLoginSessionUpdateOne {
	_u.mutation.SetIdleExpiresTime(v)
	return _u
}

// SetNillableIdleExpiresTime sets the "idle_expires_time" field if the given value is not nil.
func (_u *IAMLoginSessionUpdateOne) SetNillableIdleExpiresTime(v *time.Time) *IAMLoginSessionUpdateOne {
	if v != nil {
		_u.SetIdleExpiresTime(*v)
	}
	return _u
}

// SetRevokedTime sets the "revoked_time" field.
func (_u *IAMLoginSessionUpdateOne) SetRevokedTime(v time.Time) *IAMLoginSessionUpdateOne {
	_u.mutation.SetRevokedTime(v)
	return _u
}

// SetNillableRevokedTime sets the "revoked_time" field if the given value is not nil.
func (_u *IAMLoginSessionUpdateOne) SetNillableRevokedTime(v *time.Time) *IAMLoginSessionUpdateOne {
	if v != nil {
		_u.SetRevokedTime(*v)
	}
	return _u
}

// ClearRevokedTime clears the value of the "revoked_time" field.
func (_u *IAMLoginSessionUpdateOne) ClearRevokedTime() *IAMLoginSessionUpdateOne {
	_u.mutation.ClearRevokedTime()
	return _u
}

// Mutation returns the IAMLoginSessionMutation object of the builder.
func (_u *IAMLoginSessionUpdateOne) Mutation() *IAMLoginSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the IAMLoginSessionUpdate builder.
func (_u *IAMLoginSessionUpdateOne) Where(ps ...predicate.IAMLoginSession) *IAMLoginSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IAMLoginSessionUpdateOne) Select(field string, fields ...string) *IAMLoginSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IAMLoginSession entity.
func (_u *IAMLoginSessionUpdateOne) Save(ctx context.Context) (*IAMLoginSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IAMLoginSessionUpdateOne) SaveX(ctx context.Context) *IAMLoginSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IAMLoginSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IAMLoginSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IAMLoginSessionUpdateOne) check() error {
	if v, ok := _u.mutation.SecretHash(); ok {
		if err := iamloginsession.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "IAMLoginSession.secret_hash": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *IAMLoginSessionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *IAMLoginSessionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *IAMLoginSessionUpdateOne) sqlSave(ctx context.Context) (_node *IAMLoginSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(iamloginsession.Table, iamloginsession.Columns, sqlgraph.NewFieldSpec(iamloginsession.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IAMLoginSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, iamloginsession.FieldID)
		for _, f := range fields {
			if !iamloginsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != iamloginsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SecretHash(); ok {
		_spec.SetField(iamloginsession.FieldSecretHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenTime(); ok {
		_spec.SetField(iamloginsession.FieldLastSeenTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IdleExpiresTime(); ok {
		_spec.SetField(iamloginsession.FieldIdleExpiresTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedTime(); ok {
		_spec.SetField(iamloginsession.FieldRevokedTime, field.TypeTime, value)
	}
	if _u.mutation.RevokedTimeCleared() {
		_spec.ClearField(iamloginsession.FieldRevokedTime, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &IAMLoginSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{iamloginsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
