// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oauthtokensession"
)

// OAuthTokenSession is the model entity for the OAuthTokenSession schema.
type OAuthTokenSession struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// IamLoginSessionID holds the value of the "iam_login_session_id" field.
	IamLoginSessionID string `json:"iam_login_session_id,omitempty"`
	// RefreshFamilyID holds the value of the "refresh_family_id" field.
	RefreshFamilyID string `json:"refresh_family_id,omitempty"`
	// Scopes holds the value of the "scopes" field.
	Scopes []string `json:"scopes,omitempty"`
	// AuthTime holds the value of the "auth_time" field.
	AuthTime time.Time `json:"auth_time,omitempty"`
	// Amr holds the value of the "amr" field.
	Amr []string `json:"amr,omitempty"`
	// RevokedTime holds the value of the "revoked_time" field.
	RevokedTime *time.Time `json:"revoked_time,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime   time.Time `json:"update_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthTokenSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthtokensession.FieldScopes, oauthtokensession.FieldAmr:
			values[i] = new([]byte)
		case oauthtokensession.FieldID, oauthtokensession.FieldUserID, oauthtokensession.FieldClientID, oauthtokensession.FieldIamLoginSessionID, oauthtokensession.FieldRefreshFamilyID:
			values[i] = new(sql.NullString)
		case oauthtokensession.FieldAuthTime, oauthtokensession.FieldRevokedTime, oauthtokensession.FieldCreateTime, oauthtokensession.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthTokenSession fields.
func (_m *OAuthTokenSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthtokensession.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case oauthtokensession.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case oauthtokensession.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case oauthtokensession.FieldIamLoginSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field iam_login_session_id", values[i])
			} else if value.Valid {
				_m.IamLoginSessionID = value.String
			}
		case oauthtokensession.FieldRefreshFamilyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_family_id", values[i])
			} else if value.Valid {
				_m.RefreshFamilyID = value.String
			}
		case oauthtokensession.FieldScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Scopes); err != nil {
					return fmt.Errorf("unmarshal field scopes: %w", err)
				}
			}
		case oauthtokensession.FieldAuthTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field auth_time", values[i])
			} else if value.Valid {
				_m.AuthTime = value.Time
			}
		case oauthtokensession.FieldAmr:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field amr", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Amr); err != nil {
					return fmt.Errorf("unmarshal field amr: %w", err)
				}
			}
		case oauthtokensession.FieldRevokedTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_time", values[i])
			} else if value.Valid {
				_m.RevokedTime = new(time.Time)
				*_m.RevokedTime = value.Time
			}
		case oauthtokensession.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case oauthtokensession.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthTokenSession.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthTokenSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OAuthTokenSession.
// Note that you need to call OAuthTokenSession.Unwrap() before calling this method if this OAuthTokenSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthTokenSession) Update() *OAuthTokenSessionUpdateOne {
	return NewOAuthTokenSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthTokenSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthTokenSession) Unwrap() *OAuthTokenSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthTokenSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthTokenSession) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthTokenSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("iam_login_session_id=")
	builder.WriteString(_m.IamLoginSessionID)
	builder.WriteString(", ")
	builder.WriteString("refresh_family_id=")
	builder.WriteString(_m.RefreshFamilyID)
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scopes))
	builder.WriteString(", ")
	builder.WriteString("auth_time=")
	builder.WriteString(_m.AuthTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("amr=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amr))
	builder.WriteString(", ")
	if v := _m.RevokedTime; v != nil {
		builder.WriteString("revoked_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OAuthTokenSessions is a parsable slice of OAuthTokenSession.
type OAuthTokenSessions []*OAuthTokenSession
