// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oauthaccesstoken"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/predicate"
)

// OAuthAccessTokenUpdate is the builder for updating OAuthAccessToken entities.
type OAuthAccessTokenUpdate struct {
	config
	hooks     []Hook
	mutation  *OAuthAccessTokenMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OAuthAccessTokenUpdate builder.
func (_u *OAuthAccessTokenUpdate) Where(ps ...predicate.OAuthAccessToken) *OAuthAccessTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthAccessTokenUpdate) SetScopes(v []string) *OAuthAccessTokenUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthAccessTokenUpdate) AppendScopes(v []string) *OAuthAccessTokenUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetRevokedTime sets the "revoked_time" field.
func (_u *OAuthAccessTokenUpdate) SetRevokedTime(v time.Time) *OAuthAccessTokenUpdate {
	_u.mutation.SetRevokedTime(v)
	return _u
}

// SetNillableRevokedTime sets the "revoked_time" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdate) SetNillableRevokedTime(v *time.Time) *OAuthAccessTokenUpdate {
	if v != nil {
		_u.SetRevokedTime(*v)
	}
	return _u
}

// ClearRevokedTime clears the value of the "revoked_time" field.
func (_u *OAuthAccessTokenUpdate) ClearRevokedTime() *OAuthAccessTokenUpdate {
	_u.mutation.ClearRevokedTime()
	return _u
}

// Mutation returns the OAuthAccessTokenMutation object of the builder.
func (_u *OAuthAccessTokenUpdate) Mutation() *OAuthAccessTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthAccessTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAccessTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthAccessTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAccessTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OAuthAccessTokenUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OAuthAccessTokenUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OAuthAccessTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(oauthaccesstoken.Table, oauthaccesstoken.Columns, sqlgraph.NewFieldSpec(oauthaccesstoken.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthaccesstoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthaccesstoken.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.RevokedTime(); ok {
		_spec.SetField(oauthaccesstoken.FieldRevokedTime, field.TypeTime, value)
	}
	if _u.mutation.RevokedTimeCleared() {
		_spec.ClearField(oauthaccesstoken.FieldRevokedTime, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthAccessTokenUpdateOne is the builder for updating a single OAuthAccessToken entity.
type OAuthAccessTokenUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OAuthAccessTokenMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetScopes sets the "scopes" field.
func (_u *OAuthAccessTokenUpdateOne) SetScopes(v []string) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthAccessTokenUpdateOne) AppendScopes(v []string) *OAuthAccessTokenUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetRevokedTime sets the "revoked_time" field.
func (_u *OAuthAccessTokenUpdateOne) SetRevokedTime(v time.Time) *OAuthAccessTokenUpdateOne {
	_u.mutation.SetRevokedTime(v)
	return _u
}

// SetNillableRevokedTime sets the "revoked_time" field if the given value is not nil.
func (_u *OAuthAccessTokenUpdateOne) SetNillableRevokedTime(v *time.Time) *OAuthAccessTokenUpdateOne {
	if v != nil {
		_u.SetRevokedTime(*v)
	}
	return _u
}

// ClearRevokedTime clears the value of the "revoked_time" field.
func (_u *OAuthAccessTokenUpdateOne) ClearRevokedTime() *OAuthAccessTokenUpdateOne {
	_u.mutation.ClearRevokedTime()
	return _u
}

// Mutation returns the OAuthAccessTokenMutation object of the builder.
func (_u *OAuthAccessTokenUpdateOne) Mutation() *OAuthAccessTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthAccessTokenUpdate builder.
func (_u *OAuthAccessTokenUpdateOne) Where(ps ...predicate.OAuthAccessToken) *OAuthAccessTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthAccessTokenUpdateOne) Select(field string, fields ...string) *OAuthAccessTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthAccessToken entity.
func (_u *OAuthAccessTokenUpdateOne) Save(ctx context.Context) (*OAuthAccessToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAccessTokenUpdateOne) SaveX(ctx context.Context) *OAuthAccessToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthAccessTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAccessTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OAuthAccessTokenUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OAuthAccessTokenUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OAuthAccessTokenUpdateOne) sqlSave(ctx context.Context) (_node *OAuthAccessToken, err error) {
	_spec := sqlgraph.NewUpdateSpec(oauthaccesstoken.Table, oauthaccesstoken.Columns, sqlgraph.NewFieldSpec(oauthaccesstoken.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthAccessToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthaccesstoken.FieldID)
		for _, f := range fields {
			if !oauthaccesstoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthaccesstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthaccesstoken.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthaccesstoken.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.RevokedTime(); ok {
		_spec.SetField(oauthaccesstoken.FieldRevokedTime, field.TypeTime, value)
	}
	if _u.mutation.RevokedTimeCleared() {
		_spec.ClearField(oauthaccesstoken.FieldRevokedTime, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &OAuthAccessToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
