// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oauthauthorizationcode"
)

// OAuthAuthorizationCodeCreate is the builder for creating a OAuthAuthorizationCode entity.
type OAuthAuthorizationCodeCreate struct {
	config
	mutation *OAuthAuthorizationCodeMutation
	hooks    []Hook
}

// SetCodeHash sets the "code_hash" field.
func (_c *OAuthAuthorizationCodeCreate) SetCodeHash(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetCodeHash(v)
	return _c
}

// SetAuthorizationRequestID sets the "authorization_request_id" field.
func (_c *OAuthAuthorizationCodeCreate) SetAuthorizationRequestID(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetAuthorizationRequestID(v)
	return _c
}

// SetTokenSessionID sets the "token_session_id" field.
func (_c *OAuthAuthorizationCodeCreate) SetTokenSessionID(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetTokenSessionID(v)
	return _c
}

// SetNillableTokenSessionID sets the "token_session_id" field if the given value is not nil.
func (_c *OAuthAuthorizationCodeCreate) SetNillableTokenSessionID(v *string) *OAuthAuthorizationCodeCreate {
	if v != nil {
		_c.SetTokenSessionID(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthAuthorizationCodeCreate) SetClientID(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *OAuthAuthorizationCodeCreate) SetSubject(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OAuthAuthorizationCodeCreate) SetRedirectURI(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthAuthorizationCodeCreate) SetScopes(v []string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetPkceChallenge sets the "pkce_challenge" field.
func (_c *OAuthAuthorizationCodeCreate) SetPkceChallenge(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetPkceChallenge(v)
	return _c
}

// SetPkceChallengeMethod sets the "pkce_challenge_method" field.
func (_c *OAuthAuthorizationCodeCreate) SetPkceChallengeMethod(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetPkceChallengeMethod(v)
	return _c
}

// SetNillablePkceChallengeMethod sets the "pkce_challenge_method" field if the given value is not nil.
func (_c *OAuthAuthorizationCodeCreate) SetNillablePkceChallengeMethod(v *string) *OAuthAuthorizationCodeCreate {
	if v != nil {
		_c.SetPkceChallengeMethod(*v)
	}
	return _c
}

// SetExpiresTime sets the "expires_time" field.
func (_c *OAuthAuthorizationCodeCreate) SetExpiresTime(v time.Time) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetExpiresTime(v)
	return _c
}

// SetConsumedTime sets the "consumed_time" field.
func (_c *OAuthAuthorizationCodeCreate) SetConsumedTime(v time.Time) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetConsumedTime(v)
	return _c
}

// SetNillableConsumedTime sets the "consumed_time" field if the given value is not nil.
func (_c *OAuthAuthorizationCodeCreate) SetNillableConsumedTime(v *time.Time) *OAuthAuthorizationCodeCreate {
	if v != nil {
		_c.SetConsumedTime(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *OAuthAuthorizationCodeCreate) SetCreateTime(v time.Time) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *OAuthAuthorizationCodeCreate) SetNillableCreateTime(v *time.Time) *OAuthAuthorizationCodeCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthAuthorizationCodeCreate) SetID(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OAuthAuthorizationCodeMutation object of the builder.
func (_c *OAuthAuthorizationCodeCreate) Mutation() *OAuthAuthorizationCodeMutation {
	return _c.mutation
}

// Save creates the OAuthAuthorizationCode in the database.
func (_c *OAuthAuthorizationCodeCreate) Save(ctx context.Context) (*OAuthAuthorizationCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthAuthorizationCodeCreate) SaveX(ctx context.Context) *OAuthAuthorizationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAuthorizationCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAuthorizationCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthAuthorizationCodeCreate) defaults() {
	if _, ok := _c.mutation.PkceChallengeMethod(); !ok {
		v := oauthauthorizationcode.DefaultPkceChallengeMethod
		_c.mutation.SetPkceChallengeMethod(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := oauthauthorizationcode.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthAuthorizationCodeCreate) check() error {
	if _, ok := _c.mutation.CodeHash(); !ok {
		return &ValidationError{Name: "code_hash", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.code_hash"`)}
	}
	if v, ok := _c.mutation.CodeHash(); ok {
		if err := oauthauthorizationcode.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.code_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorizationRequestID(); !ok {
		return &ValidationError{Name: "authorization_request_id", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.authorization_request_id"`)}
	}
	if v, ok := _c.mutation.AuthorizationRequestID(); ok {
		if err := oauthauthorizationcode.AuthorizationRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "authorization_request_id", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.authorization_request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthauthorizationcode.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := oauthauthorizationcode.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.redirect_uri"`)}
	}
	if v, ok := _c.mutation.RedirectURI(); ok {
		if err := oauthauthorizationcode.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.redirect_uri": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.scopes"`)}
	}
	if _, ok := _c.mutation.PkceChallenge(); !ok {
		return &ValidationError{Name: "pkce_challenge", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.pkce_challenge"`)}
	}
	if v, ok := _c.mutation.PkceChallenge(); ok {
		if err := oauthauthorizationcode.PkceChallengeValidator(v); err != nil {
			return &ValidationError{Name: "pkce_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.pkce_challenge": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PkceChallengeMethod(); !ok {
		return &ValidationError{Name: "pkce_challenge_method", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.pkce_challenge_method"`)}
	}
	if _, ok := _c.mutation.ExpiresTime(); !ok {
		return &ValidationError{Name: "expires_time", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.expires_time"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.create_time"`)}
	}
	return nil
}

func (_c *OAuthAuthorizationCodeCreate) sqlSave(ctx context.Context) (*OAuthAuthorizationCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected OAuthAuthorizationCode.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthAuthorizationCodeCreate) createSpec() (*OAuthAuthorizationCode, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthAuthorizationCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthauthorizationcode.Table, sqlgraph.NewFieldSpec(oauthauthorizationcode.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CodeHash(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCodeHash, field.TypeString, value)
		_node.CodeHash = value
	}
	if value, ok := _c.mutation.AuthorizationRequestID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldAuthorizationRequestID, field.TypeString, value)
		_node.AuthorizationRequestID = value
	}
	if value, ok := _c.mutation.TokenSessionID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldTokenSessionID, field.TypeString, value)
		_node.TokenSessionID = &value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(oauthauthorizationcode.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oauthauthorizationcode.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthauthorizationcode.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.PkceChallenge(); ok {
		_spec.SetField(oauthauthorizationcode.FieldPkceChallenge, field.TypeString, value)
		_node.PkceChallenge = value
	}
	if value, ok := _c.mutation.PkceChallengeMethod(); ok {
		_spec.SetField(oauthauthorizationcode.FieldPkceChallengeMethod, field.TypeString, value)
		_node.PkceChallengeMethod = value
	}
	if value, ok := _c.mutation.ExpiresTime(); ok {
		_spec.SetField(oauthauthorizationcode.FieldExpiresTime, field.TypeTime, value)
		_node.ExpiresTime = value
	}
	if value, ok := _c.mutation.ConsumedTime(); ok {
		_spec.SetField(oauthauthorizationcode.FieldConsumedTime, field.TypeTime, value)
		_node.ConsumedTime = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	return _node, _spec
}

// OAuthAuthorizationCodeCreateBulk is the builder for creating many OAuthAuthorizationCode entities in bulk.
type OAuthAuthorizationCodeCreateBulk struct {
	config
	err      error
	builders []*OAuthAuthorizationCodeCreate
}

// Save creates the OAuthAuthorizationCode entities in the database.
func (_c *OAuthAuthorizationCodeCreateBulk) Save(ctx context.Context) ([]*OAuthAuthorizationCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthAuthorizationCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthAuthorizationCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthAuthorizationCodeCreateBulk) SaveX(ctx context.Context) []*OAuthAuthorizationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAuthorizationCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAuthorizationCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
