// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oauthauthorizationcode"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/predicate"
)

// OAuthAuthorizationCodeUpdate is the builder for updating OAuthAuthorizationCode entities.
type OAuthAuthorizationCodeUpdate struct {
	config
	hooks     []Hook
	mutation  *OAuthAuthorizationCodeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OAuthAuthorizationCodeUpdate builder.
func (_u *OAuthAuthorizationCodeUpdate) Where(ps ...predicate.OAuthAuthorizationCode) *OAuthAuthorizationCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *OAuthAuthorizationCodeUpdate) SetCodeHash(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableCodeHash(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// SetTokenSessionID sets the "token_session_id" field.
func (_u *OAuthAuthorizationCodeUpdate) SetTokenSessionID(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetTokenSessionID(v)
	return _u
}

// SetNillableTokenSessionID sets the "token_session_id" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableTokenSessionID(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetTokenSessionID(*v)
	}
	return _u
}

// ClearTokenSessionID clears the value of the "token_session_id" field.
func (_u *OAuthAuthorizationCodeUpdate) ClearTokenSessionID() *OAuthAuthorizationCodeUpdate {
	_u.mutation.ClearTokenSessionID()
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthAuthorizationCodeUpdate) SetScopes(v []string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthAuthorizationCodeUpdate) AppendScopes(v []string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetPkceChallenge sets the "pkce_challenge" field.
func (_u *OAuthAuthorizationCodeUpdate) SetPkceChallenge(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetPkceChallenge(v)
	return _u
}

// SetNillablePkceChallenge sets the "pkce_challenge" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillablePkceChallenge(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetPkceChallenge(*v)
	}
	return _u
}

// SetPkceChallengeMethod sets the "pkce_challenge_method" field.
func (_u *OAuthAuthorizationCodeUpdate) SetPkceChallengeMethod(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetPkceChallengeMethod(v)
	return _u
}

// SetNillablePkceChallengeMethod sets the "pkce_challenge_method" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillablePkceChallengeMethod(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetPkceChallengeMethod(*v)
	}
	return _u
}

// SetConsumedTime sets the "consumed_time" field.
func (_u *OAuthAuthorizationCodeUpdate) SetConsumedTime(v time.Time) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetConsumedTime(v)
	return _u
}

// SetNillableConsumedTime sets the "consumed_time" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableConsumedTime(v *time.Time) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetConsumedTime(*v)
	}
	return _u
}

// ClearConsumedTime clears the value of the "consumed_time" field.
func (_u *OAuthAuthorizationCodeUpdate) ClearConsumedTime() *OAuthAuthorizationCodeUpdate {
	_u.mutation.ClearConsumedTime()
	return _u
}

// Mutation returns the OAuthAuthorizationCodeMutation object of the builder.
func (_u *OAuthAuthorizationCodeUpdate) Mutation() *OAuthAuthorizationCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthAuthorizationCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAuthorizationCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthAuthorizationCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAuthorizationCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAuthorizationCodeUpdate) check() error {
	if v, ok := _u.mutation.CodeHash(); ok {
		if err := oauthauthorizationcode.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.code_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PkceChallenge(); ok {
		if err := oauthauthorizationcode.PkceChallengeValidator(v); err != nil {
			return &ValidationError{Name: "pkce_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.pkce_challenge": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OAuthAuthorizationCodeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OAuthAuthorizationCodeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OAuthAuthorizationCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthauthorizationcode.Table, oauthauthorizationcode.Columns, sqlgraph.NewFieldSpec(oauthauthorizationcode.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCodeHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenSessionID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldTokenSessionID, field.TypeString, value)
	}
	if _u.mutation.TokenSessionIDCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldTokenSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthauthorizationcode.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthauthorizationcode.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.PkceChallenge(); ok {
		_spec.SetField(oauthauthorizationcode.FieldPkceChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.PkceChallengeMethod(); ok {
		_spec.SetField(oauthauthorizationcode.FieldPkceChallengeMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsumedTime(); ok {
		_spec.SetField(oauthauthorizationcode.FieldConsumedTime, field.TypeTime, value)
	}
	if _u.mutation.ConsumedTimeCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldConsumedTime, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthauthorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthAuthorizationCodeUpdateOne is the builder for updating a single OAuthAuthorizationCode entity.
type OAuthAuthorizationCodeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OAuthAuthorizationCodeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCodeHash sets the "code_hash" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetCodeHash(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableCodeHash(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// SetTokenSessionID sets the "token_session_id" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetTokenSessionID(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetTokenSessionID(v)
	return _u
}

// SetNillableTokenSessionID sets the "token_session_id" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableTokenSessionID(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetTokenSessionID(*v)
	}
	return _u
}

// ClearTokenSessionID clears the value of the "token_session_id" field.
func (_u *OAuthAuthorizationCodeUpdateOne) ClearTokenSessionID() *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.ClearTokenSessionID()
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetScopes(v []string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthAuthorizationCodeUpdateOne) AppendScopes(v []string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetPkceChallenge sets the "pkce_challenge" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetPkceChallenge(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetPkceChallenge(v)
	return _u
}

// SetNillablePkceChallenge sets the "pkce_challenge" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillablePkceChallenge(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetPkceChallenge(*v)
	}
	return _u
}

// SetPkceChallengeMethod sets the "pkce_challenge_method" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetPkceChallengeMethod(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetPkceChallengeMethod(v)
	return _u
}

// SetNillablePkceChallengeMethod sets the "pkce_challenge_method" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillablePkceChallengeMethod(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetPkceChallengeMethod(*v)
	}
	return _u
}

// SetConsumedTime sets the "consumed_time" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetConsumedTime(v time.Time) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetConsumedTime(v)
	return _u
}

// SetNillableConsumedTime sets the "consumed_time" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableConsumedTime(v *time.Time) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetConsumedTime(*v)
	}
	return _u
}

// ClearConsumedTime clears the value of the "consumed_time" field.
func (_u *OAuthAuthorizationCodeUpdateOne) ClearConsumedTime() *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.ClearConsumedTime()
	return _u
}

// Mutation returns the OAuthAuthorizationCodeMutation object of the builder.
func (_u *OAuthAuthorizationCodeUpdateOne) Mutation() *OAuthAuthorizationCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthAuthorizationCodeUpdate builder.
func (_u *OAuthAuthorizationCodeUpdateOne) Where(ps ...predicate.OAuthAuthorizationCode) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthAuthorizationCodeUpdateOne) Select(field string, fields ...string) *OAuthAuthorizationCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthAuthorizationCode entity.
func (_u *OAuthAuthorizationCodeUpdateOne) Save(ctx context.Context) (*OAuthAuthorizationCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAuthorizationCodeUpdateOne) SaveX(ctx context.Context) *OAuthAuthorizationCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthAuthorizationCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAuthorizationCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAuthorizationCodeUpdateOne) check() error {
	if v, ok := _u.mutation.CodeHash(); ok {
		if err := oauthauthorizationcode.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.code_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PkceChallenge(); ok {
		if err := oauthauthorizationcode.PkceChallengeValidator(v); err != nil {
			return &ValidationError{Name: "pkce_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.pkce_challenge": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OAuthAuthorizationCodeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OAuthAuthorizationCodeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OAuthAuthorizationCodeUpdateOne) sqlSave(ctx context.Context) (_node *OAuthAuthorizationCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthauthorizationcode.Table, oauthauthorizationcode.Columns, sqlgraph.NewFieldSpec(oauthauthorizationcode.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthAuthorizationCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthauthorizationcode.FieldID)
		for _, f := range fields {
			if !oauthauthorizationcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthauthorizationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCodeHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenSessionID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldTokenSessionID, field.TypeString, value)
	}
	if _u.mutation.TokenSessionIDCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldTokenSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthauthorizationcode.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthauthorizationcode.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.PkceChallenge(); ok {
		_spec.SetField(oauthauthorizationcode.FieldPkceChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.PkceChallengeMethod(); ok {
		_spec.SetField(oauthauthorizationcode.FieldPkceChallengeMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsumedTime(); ok {
		_spec.SetField(oauthauthorizationcode.FieldConsumedTime, field.TypeTime, value)
	}
	if _u.mutation.ConsumedTimeCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldConsumedTime, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &OAuthAuthorizationCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthauthorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
