// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oauthauthorizationcode"
)

// OAuthAuthorizationCode is the model entity for the OAuthAuthorizationCode schema.
type OAuthAuthorizationCode struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CodeHash holds the value of the "code_hash" field.
	CodeHash string `json:"-"`
	// AuthorizationRequestID holds the value of the "authorization_request_id" field.
	AuthorizationRequestID string `json:"authorization_request_id,omitempty"`
	// TokenSessionID holds the value of the "token_session_id" field.
	TokenSessionID *string `json:"token_session_id,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// RedirectURI holds the value of the "redirect_uri" field.
	RedirectURI string `json:"redirect_uri,omitempty"`
	// Scopes holds the value of the "scopes" field.
	Scopes []string `json:"scopes,omitempty"`
	// PkceChallenge holds the value of the "pkce_challenge" field.
	PkceChallenge string `json:"-"`
	// PkceChallengeMethod holds the value of the "pkce_challenge_method" field.
	PkceChallengeMethod string `json:"pkce_challenge_method,omitempty"`
	// ExpiresTime holds the value of the "expires_time" field.
	ExpiresTime time.Time `json:"expires_time,omitempty"`
	// ConsumedTime holds the value of the "consumed_time" field.
	ConsumedTime *time.Time `json:"consumed_time,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime   time.Time `json:"create_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthAuthorizationCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthauthorizationcode.FieldScopes:
			values[i] = new([]byte)
		case oauthauthorizationcode.FieldID, oauthauthorizationcode.FieldCodeHash, oauthauthorizationcode.FieldAuthorizationRequestID, oauthauthorizationcode.FieldTokenSessionID, oauthauthorizationcode.FieldClientID, oauthauthorizationcode.FieldSubject, oauthauthorizationcode.FieldRedirectURI, oauthauthorizationcode.FieldPkceChallenge, oauthauthorizationcode.FieldPkceChallengeMethod:
			values[i] = new(sql.NullString)
		case oauthauthorizationcode.FieldExpiresTime, oauthauthorizationcode.FieldConsumedTime, oauthauthorizationcode.FieldCreateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthAuthorizationCode fields.
func (_m *OAuthAuthorizationCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthauthorizationcode.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case oauthauthorizationcode.FieldCodeHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_hash", values[i])
			} else if value.Valid {
				_m.CodeHash = value.String
			}
		case oauthauthorizationcode.FieldAuthorizationRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field authorization_request_id", values[i])
			} else if value.Valid {
				_m.AuthorizationRequestID = value.String
			}
		case oauthauthorizationcode.FieldTokenSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_session_id", values[i])
			} else if value.Valid {
				_m.TokenSessionID = new(string)
				*_m.TokenSessionID = value.String
			}
		case oauthauthorizationcode.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case oauthauthorizationcode.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case oauthauthorizationcode.FieldRedirectURI:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redirect_uri", values[i])
			} else if value.Valid {
				_m.RedirectURI = value.String
			}
		case oauthauthorizationcode.FieldScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Scopes); err != nil {
					return fmt.Errorf("unmarshal field scopes: %w", err)
				}
			}
		case oauthauthorizationcode.FieldPkceChallenge:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pkce_challenge", values[i])
			} else if value.Valid {
				_m.PkceChallenge = value.String
			}
		case oauthauthorizationcode.FieldPkceChallengeMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pkce_challenge_method", values[i])
			} else if value.Valid {
				_m.PkceChallengeMethod = value.String
			}
		case oauthauthorizationcode.FieldExpiresTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_time", values[i])
			} else if value.Valid {
				_m.ExpiresTime = value.Time
			}
		case oauthauthorizationcode.FieldConsumedTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_time", values[i])
			} else if value.Valid {
				_m.ConsumedTime = new(time.Time)
				*_m.ConsumedTime = value.Time
			}
		case oauthauthorizationcode.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthAuthorizationCode.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthAuthorizationCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OAuthAuthorizationCode.
// Note that you need to call OAuthAuthorizationCode.Unwrap() before calling this method if this OAuthAuthorizationCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthAuthorizationCode) Update() *OAuthAuthorizationCodeUpdateOne {
	return NewOAuthAuthorizationCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthAuthorizationCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthAuthorizationCode) Unwrap() *OAuthAuthorizationCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthAuthorizationCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthAuthorizationCode) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthAuthorizationCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("authorization_request_id=")
	builder.WriteString(_m.AuthorizationRequestID)
	builder.WriteString(", ")
	if v := _m.TokenSessionID; v != nil {
		builder.WriteString("token_session_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("redirect_uri=")
	builder.WriteString(_m.RedirectURI)
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scopes))
	builder.WriteString(", ")
	builder.WriteString("pkce_challenge=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("pkce_challenge_method=")
	builder.WriteString(_m.PkceChallengeMethod)
	builder.WriteString(", ")
	builder.WriteString("expires_time=")
	builder.WriteString(_m.ExpiresTime.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConsumedTime; v != nil {
		builder.WriteString("consumed_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OAuthAuthorizationCodes is a parsable slice of OAuthAuthorizationCode.
type OAuthAuthorizationCodes []*OAuthAuthorizationCode
