// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oauthrefreshtoken"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/predicate"
)

// OAuthRefreshTokenUpdate is the builder for updating OAuthRefreshToken entities.
type OAuthRefreshTokenUpdate struct {
	config
	hooks     []Hook
	mutation  *OAuthRefreshTokenMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OAuthRefreshTokenUpdate builder.
func (_u *OAuthRefreshTokenUpdate) Where(ps ...predicate.OAuthRefreshToken) *OAuthRefreshTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *OAuthRefreshTokenUpdate) SetTokenHash(v string) *OAuthRefreshTokenUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableTokenHash(v *string) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetConsumedTime sets the "consumed_time" field.
func (_u *OAuthRefreshTokenUpdate) SetConsumedTime(v time.Time) *OAuthRefreshTokenUpdate {
	_u.mutation.SetConsumedTime(v)
	return _u
}

// SetNillableConsumedTime sets the "consumed_time" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableConsumedTime(v *time.Time) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetConsumedTime(*v)
	}
	return _u
}

// ClearConsumedTime clears the value of the "consumed_time" field.
func (_u *OAuthRefreshTokenUpdate) ClearConsumedTime() *OAuthRefreshTokenUpdate {
	_u.mutation.ClearConsumedTime()
	return _u
}

// SetRevokedTime sets the "revoked_time" field.
func (_u *OAuthRefreshTokenUpdate) SetRevokedTime(v time.Time) *OAuthRefreshTokenUpdate {
	_u.mutation.SetRevokedTime(v)
	return _u
}

// SetNillableRevokedTime sets the "revoked_time" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdate) SetNillableRevokedTime(v *time.Time) *OAuthRefreshTokenUpdate {
	if v != nil {
		_u.SetRevokedTime(*v)
	}
	return _u
}

// ClearRevokedTime clears the value of the "revoked_time" field.
func (_u *OAuthRefreshTokenUpdate) ClearRevokedTime() *OAuthRefreshTokenUpdate {
	_u.mutation.ClearRevokedTime()
	return _u
}

// Mutation returns the OAuthRefreshTokenMutation object of the builder.
func (_u *OAuthRefreshTokenUpdate) Mutation() *OAuthRefreshTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthRefreshTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRefreshTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthRefreshTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRefreshTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRefreshTokenUpdate) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := oauthrefreshtoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthRefreshToken.token_hash": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OAuthRefreshTokenUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OAuthRefreshTokenUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OAuthRefreshTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthrefreshtoken.Table, oauthrefreshtoken.Columns, sqlgraph.NewFieldSpec(oauthrefreshtoken.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oauthrefreshtoken.FieldTokenHash, field.TypeString, value)
	}
	if _u.mutation.ParentTokenIDCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldParentTokenID, field.TypeString)
	}
	if value, ok := _u.mutation.ConsumedTime(); ok {
		_spec.SetField(oauthrefreshtoken.FieldConsumedTime, field.TypeTime, value)
	}
	if _u.mutation.ConsumedTimeCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldConsumedTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedTime(); ok {
		_spec.SetField(oauthrefreshtoken.FieldRevokedTime, field.TypeTime, value)
	}
	if _u.mutation.RevokedTimeCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldRevokedTime, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthrefreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthRefreshTokenUpdateOne is the builder for updating a single OAuthRefreshToken entity.
type OAuthRefreshTokenUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OAuthRefreshTokenMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTokenHash sets the "token_hash" field.
func (_u *OAuthRefreshTokenUpdateOne) SetTokenHash(v string) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableTokenHash(v *string) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetConsumedTime sets the "consumed_time" field.
func (_u *OAuthRefreshTokenUpdateOne) SetConsumedTime(v time.Time) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetConsumedTime(v)
	return _u
}

// SetNillableConsumedTime sets the "consumed_time" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableConsumedTime(v *time.Time) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetConsumedTime(*v)
	}
	return _u
}

// ClearConsumedTime clears the value of the "consumed_time" field.
func (_u *OAuthRefreshTokenUpdateOne) ClearConsumedTime() *OAuthRefreshTokenUpdateOne {
	_u.mutation.ClearConsumedTime()
	return _u
}

// SetRevokedTime sets the "revoked_time" field.
func (_u *OAuthRefreshTokenUpdateOne) SetRevokedTime(v time.Time) *OAuthRefreshTokenUpdateOne {
	_u.mutation.SetRevokedTime(v)
	return _u
}

// SetNillableRevokedTime sets the "revoked_time" field if the given value is not nil.
func (_u *OAuthRefreshTokenUpdateOne) SetNillableRevokedTime(v *time.Time) *OAuthRefreshTokenUpdateOne {
	if v != nil {
		_u.SetRevokedTime(*v)
	}
	return _u
}

// ClearRevokedTime clears the value of the "revoked_time" field.
func (_u *OAuthRefreshTokenUpdateOne) ClearRevokedTime() *OAuthRefreshTokenUpdateOne {
	_u.mutation.ClearRevokedTime()
	return _u
}

// Mutation returns the OAuthRefreshTokenMutation object of the builder.
func (_u *OAuthRefreshTokenUpdateOne) Mutation() *OAuthRefreshTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthRefreshTokenUpdate builder.
func (_u *OAuthRefreshTokenUpdateOne) Where(ps ...predicate.OAuthRefreshToken) *OAuthRefreshTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthRefreshTokenUpdateOne) Select(field string, fields ...string) *OAuthRefreshTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthRefreshToken entity.
func (_u *OAuthRefreshTokenUpdateOne) Save(ctx context.Context) (*OAuthRefreshToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRefreshTokenUpdateOne) SaveX(ctx context.Context) *OAuthRefreshToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthRefreshTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRefreshTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRefreshTokenUpdateOne) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := oauthrefreshtoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthRefreshToken.token_hash": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OAuthRefreshTokenUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OAuthRefreshTokenUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OAuthRefreshTokenUpdateOne) sqlSave(ctx context.Context) (_node *OAuthRefreshToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthrefreshtoken.Table, oauthrefreshtoken.Columns, sqlgraph.NewFieldSpec(oauthrefreshtoken.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthRefreshToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthrefreshtoken.FieldID)
		for _, f := range fields {
			if !oauthrefreshtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthrefreshtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oauthrefreshtoken.FieldTokenHash, field.TypeString, value)
	}
	if _u.mutation.ParentTokenIDCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldParentTokenID, field.TypeString)
	}
	if value, ok := _u.mutation.ConsumedTime(); ok {
		_spec.SetField(oauthrefreshtoken.FieldConsumedTime, field.TypeTime, value)
	}
	if _u.mutation.ConsumedTimeCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldConsumedTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedTime(); ok {
		_spec.SetField(oauthrefreshtoken.FieldRevokedTime, field.TypeTime, value)
	}
	if _u.mutation.RevokedTimeCleared() {
		_spec.ClearField(oauthrefreshtoken.FieldRevokedTime, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &OAuthRefreshToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthrefreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
