// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oidcsigningkey"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/predicate"
)

// OIDCSigningKeyUpdate is the builder for updating OIDCSigningKey entities.
type OIDCSigningKeyUpdate struct {
	config
	hooks     []Hook
	mutation  *OIDCSigningKeyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OIDCSigningKeyUpdate builder.
func (_u *OIDCSigningKeyUpdate) Where(ps ...predicate.OIDCSigningKey) *OIDCSigningKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPublicJwk sets the "public_jwk" field.
func (_u *OIDCSigningKeyUpdate) SetPublicJwk(v string) *OIDCSigningKeyUpdate {
	_u.mutation.SetPublicJwk(v)
	return _u
}

// SetNillablePublicJwk sets the "public_jwk" field if the given value is not nil.
func (_u *OIDCSigningKeyUpdate) SetNillablePublicJwk(v *string) *OIDCSigningKeyUpdate {
	if v != nil {
		_u.SetPublicJwk(*v)
	}
	return _u
}

// SetRevokedTime sets the "revoked_time" field.
func (_u *OIDCSigningKeyUpdate) SetRevokedTime(v time.Time) *OIDCSigningKeyUpdate {
	_u.mutation.SetRevokedTime(v)
	return _u
}

// SetNillableRevokedTime sets the "revoked_time" field if the given value is not nil.
func (_u *OIDCSigningKeyUpdate) SetNillableRevokedTime(v *time.Time) *OIDCSigningKeyUpdate {
	if v != nil {
		_u.SetRevokedTime(*v)
	}
	return _u
}

// ClearRevokedTime clears the value of the "revoked_time" field.
func (_u *OIDCSigningKeyUpdate) ClearRevokedTime() *OIDCSigningKeyUpdate {
	_u.mutation.ClearRevokedTime()
	return _u
}

// Mutation returns the OIDCSigningKeyMutation object of the builder.
func (_u *OIDCSigningKeyUpdate) Mutation() *OIDCSigningKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OIDCSigningKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCSigningKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OIDCSigningKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCSigningKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OIDCSigningKeyUpdate) check() error {
	if v, ok := _u.mutation.PublicJwk(); ok {
		if err := oidcsigningkey.PublicJwkValidator(v); err != nil {
			return &ValidationError{Name: "public_jwk", err: fmt.Errorf(`ent: validator failed for field "OIDCSigningKey.public_jwk": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OIDCSigningKeyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OIDCSigningKeyUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OIDCSigningKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oidcsigningkey.Table, oidcsigningkey.Columns, sqlgraph.NewFieldSpec(oidcsigningkey.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicJwk(); ok {
		_spec.SetField(oidcsigningkey.FieldPublicJwk, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevokedTime(); ok {
		_spec.SetField(oidcsigningkey.FieldRevokedTime, field.TypeTime, value)
	}
	if _u.mutation.RevokedTimeCleared() {
		_spec.ClearField(oidcsigningkey.FieldRevokedTime, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcsigningkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OIDCSigningKeyUpdateOne is the builder for updating a single OIDCSigningKey entity.
type OIDCSigningKeyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OIDCSigningKeyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetPublicJwk sets the "public_jwk" field.
func (_u *OIDCSigningKeyUpdateOne) SetPublicJwk(v string) *OIDCSigningKeyUpdateOne {
	_u.mutation.SetPublicJwk(v)
	return _u
}

// SetNillablePublicJwk sets the "public_jwk" field if the given value is not nil.
func (_u *OIDCSigningKeyUpdateOne) SetNillablePublicJwk(v *string) *OIDCSigningKeyUpdateOne {
	if v != nil {
		_u.SetPublicJwk(*v)
	}
	return _u
}

// SetRevokedTime sets the "revoked_time" field.
func (_u *OIDCSigningKeyUpdateOne) SetRevokedTime(v time.Time) *OIDCSigningKeyUpdateOne {
	_u.mutation.SetRevokedTime(v)
	return _u
}

// SetNillableRevokedTime sets the "revoked_time" field if the given value is not nil.
func (_u *OIDCSigningKeyUpdateOne) SetNillableRevokedTime(v *time.Time) *OIDCSigningKeyUpdateOne {
	if v != nil {
		_u.SetRevokedTime(*v)
	}
	return _u
}

// ClearRevokedTime clears the value of the "revoked_time" field.
func (_u *OIDCSigningKeyUpdateOne) ClearRevokedTime() *OIDCSigningKeyUpdateOne {
	_u.mutation.ClearRevokedTime()
	return _u
}

// Mutation returns the OIDCSigningKeyMutation object of the builder.
func (_u *OIDCSigningKeyUpdateOne) Mutation() *OIDCSigningKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the OIDCSigningKeyUpdate builder.
func (_u *OIDCSigningKeyUpdateOne) Where(ps ...predicate.OIDCSigningKey) *OIDCSigningKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OIDCSigningKeyUpdateOne) Select(field string, fields ...string) *OIDCSigningKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OIDCSigningKey entity.
func (_u *OIDCSigningKeyUpdateOne) Save(ctx context.Context) (*OIDCSigningKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCSigningKeyUpdateOne) SaveX(ctx context.Context) *OIDCSigningKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OIDCSigningKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCSigningKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OIDCSigningKeyUpdateOne) check() error {
	if v, ok := _u.mutation.PublicJwk(); ok {
		if err := oidcsigningkey.PublicJwkValidator(v); err != nil {
			return &ValidationError{Name: "public_jwk", err: fmt.Errorf(`ent: validator failed for field "OIDCSigningKey.public_jwk": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OIDCSigningKeyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OIDCSigningKeyUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OIDCSigningKeyUpdateOne) sqlSave(ctx context.Context) (_node *OIDCSigningKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oidcsigningkey.Table, oidcsigningkey.Columns, sqlgraph.NewFieldSpec(oidcsigningkey.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OIDCSigningKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oidcsigningkey.FieldID)
		for _, f := range fields {
			if !oidcsigningkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oidcsigningkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicJwk(); ok {
		_spec.SetField(oidcsigningkey.FieldPublicJwk, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevokedTime(); ok {
		_spec.SetField(oidcsigningkey.FieldRevokedTime, field.TypeTime, value)
	}
	if _u.mutation.RevokedTimeCleared() {
		_spec.ClearField(oidcsigningkey.FieldRevokedTime, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &OIDCSigningKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcsigningkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
