// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oidcsigningkey"
)

// OIDCSigningKeyCreate is the builder for creating a OIDCSigningKey entity.
type OIDCSigningKeyCreate struct {
	config
	mutation *OIDCSigningKeyMutation
	hooks    []Hook
}

// SetPublicJwk sets the "public_jwk" field.
func (_c *OIDCSigningKeyCreate) SetPublicJwk(v string) *OIDCSigningKeyCreate {
	_c.mutation.SetPublicJwk(v)
	return _c
}

// SetAlgorithm sets the "algorithm" field.
func (_c *OIDCSigningKeyCreate) SetAlgorithm(v string) *OIDCSigningKeyCreate {
	_c.mutation.SetAlgorithm(v)
	return _c
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (_c *OIDCSigningKeyCreate) SetNillableAlgorithm(v *string) *OIDCSigningKeyCreate {
	if v != nil {
		_c.SetAlgorithm(*v)
	}
	return _c
}

// SetNotBeforeTime sets the "not_before_time" field.
func (_c *OIDCSigningKeyCreate) SetNotBeforeTime(v time.Time) *OIDCSigningKeyCreate {
	_c.mutation.SetNotBeforeTime(v)
	return _c
}

// SetExpiresTime sets the "expires_time" field.
func (_c *OIDCSigningKeyCreate) SetExpiresTime(v time.Time) *OIDCSigningKeyCreate {
	_c.mutation.SetExpiresTime(v)
	return _c
}

// SetRevokedTime sets the "revoked_time" field.
func (_c *OIDCSigningKeyCreate) SetRevokedTime(v time.Time) *OIDCSigningKeyCreate {
	_c.mutation.SetRevokedTime(v)
	return _c
}

// SetNillableRevokedTime sets the "revoked_time" field if the given value is not nil.
func (_c *OIDCSigningKeyCreate) SetNillableRevokedTime(v *time.Time) *OIDCSigningKeyCreate {
	if v != nil {
		_c.SetRevokedTime(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *OIDCSigningKeyCreate) SetCreateTime(v time.Time) *OIDCSigningKeyCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *OIDCSigningKeyCreate) SetNillableCreateTime(v *time.Time) *OIDCSigningKeyCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OIDCSigningKeyCreate) SetID(v string) *OIDCSigningKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OIDCSigningKeyMutation object of the builder.
func (_c *OIDCSigningKeyCreate) Mutation() *OIDCSigningKeyMutation {
	return _c.mutation
}

// Save creates the OIDCSigningKey in the database.
func (_c *OIDCSigningKeyCreate) Save(ctx context.Context) (*OIDCSigningKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OIDCSigningKeyCreate) SaveX(ctx context.Context) *OIDCSigningKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCSigningKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCSigningKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OIDCSigningKeyCreate) defaults() {
	if _, ok := _c.mutation.Algorithm(); !ok {
		v := oidcsigningkey.DefaultAlgorithm
		_c.mutation.SetAlgorithm(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := oidcsigningkey.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OIDCSigningKeyCreate) check() error {
	if _, ok := _c.mutation.PublicJwk(); !ok {
		return &ValidationError{Name: "public_jwk", err: errors.New(`ent: missing required field "OIDCSigningKey.public_jwk"`)}
	}
	if v, ok := _c.mutation.PublicJwk(); ok {
		if err := oidcsigningkey.PublicJwkValidator(v); err != nil {
			return &ValidationError{Name: "public_jwk", err: fmt.Errorf(`ent: validator failed for field "OIDCSigningKey.public_jwk": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Algorithm(); !ok {
		return &ValidationError{Name: "algorithm", err: errors.New(`ent: missing required field "OIDCSigningKey.algorithm"`)}
	}
	if _, ok := _c.mutation.NotBeforeTime(); !ok {
		return &ValidationError{Name: "not_before_time", err: errors.New(`ent: missing required field "OIDCSigningKey.not_before_time"`)}
	}
	if _, ok := _c.mutation.ExpiresTime(); !ok {
		return &ValidationError{Name: "expires_time", err: errors.New(`ent: missing required field "OIDCSigningKey.expires_time"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "OIDCSigningKey.create_time"`)}
	}
	return nil
}

func (_c *OIDCSigningKeyCreate) sqlSave(ctx context.Context) (*OIDCSigningKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected OIDCSigningKey.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OIDCSigningKeyCreate) createSpec() (*OIDCSigningKey, *sqlgraph.CreateSpec) {
	var (
		_node = &OIDCSigningKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oidcsigningkey.Table, sqlgraph.NewFieldSpec(oidcsigningkey.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PublicJwk(); ok {
		_spec.SetField(oidcsigningkey.FieldPublicJwk, field.TypeString, value)
		_node.PublicJwk = value
	}
	if value, ok := _c.mutation.Algorithm(); ok {
		_spec.SetField(oidcsigningkey.FieldAlgorithm, field.TypeString, value)
		_node.Algorithm = value
	}
	if value, ok := _c.mutation.NotBeforeTime(); ok {
		_spec.SetField(oidcsigningkey.FieldNotBeforeTime, field.TypeTime, value)
		_node.NotBeforeTime = value
	}
	if value, ok := _c.mutation.ExpiresTime(); ok {
		_spec.SetField(oidcsigningkey.FieldExpiresTime, field.TypeTime, value)
		_node.ExpiresTime = value
	}
	if value, ok := _c.mutation.RevokedTime(); ok {
		_spec.SetField(oidcsigningkey.FieldRevokedTime, field.TypeTime, value)
		_node.RevokedTime = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(oidcsigningkey.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	return _node, _spec
}

// OIDCSigningKeyCreateBulk is the builder for creating many OIDCSigningKey entities in bulk.
type OIDCSigningKeyCreateBulk struct {
	config
	err      error
	builders []*OIDCSigningKeyCreate
}

// Save creates the OIDCSigningKey entities in the database.
func (_c *OIDCSigningKeyCreateBulk) Save(ctx context.Context) ([]*OIDCSigningKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OIDCSigningKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OIDCSigningKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OIDCSigningKeyCreateBulk) SaveX(ctx context.Context) []*OIDCSigningKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OIDCSigningKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OIDCSigningKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
