// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/passwordauthenticator"
)

// PasswordAuthenticatorCreate is the builder for creating a PasswordAuthenticator entity.
type PasswordAuthenticatorCreate struct {
	config
	mutation *PasswordAuthenticatorMutation
	hooks    []Hook
}

// SetAuthenticatorID sets the "authenticator_id" field.
func (_c *PasswordAuthenticatorCreate) SetAuthenticatorID(v string) *PasswordAuthenticatorCreate {
	_c.mutation.SetAuthenticatorID(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *PasswordAuthenticatorCreate) SetPasswordHash(v string) *PasswordAuthenticatorCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetChangedTime sets the "changed_time" field.
func (_c *PasswordAuthenticatorCreate) SetChangedTime(v time.Time) *PasswordAuthenticatorCreate {
	_c.mutation.SetChangedTime(v)
	return _c
}

// SetNillableChangedTime sets the "changed_time" field if the given value is not nil.
func (_c *PasswordAuthenticatorCreate) SetNillableChangedTime(v *time.Time) *PasswordAuthenticatorCreate {
	if v != nil {
		_c.SetChangedTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PasswordAuthenticatorCreate) SetID(v string) *PasswordAuthenticatorCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PasswordAuthenticatorMutation object of the builder.
func (_c *PasswordAuthenticatorCreate) Mutation() *PasswordAuthenticatorMutation {
	return _c.mutation
}

// Save creates the PasswordAuthenticator in the database.
func (_c *PasswordAuthenticatorCreate) Save(ctx context.Context) (*PasswordAuthenticator, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PasswordAuthenticatorCreate) SaveX(ctx context.Context) *PasswordAuthenticator {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasswordAuthenticatorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasswordAuthenticatorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PasswordAuthenticatorCreate) defaults() {
	if _, ok := _c.mutation.ChangedTime(); !ok {
		v := passwordauthenticator.DefaultChangedTime()
		_c.mutation.SetChangedTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PasswordAuthenticatorCreate) check() error {
	if _, ok := _c.mutation.AuthenticatorID(); !ok {
		return &ValidationError{Name: "authenticator_id", err: errors.New(`ent: missing required field "PasswordAuthenticator.authenticator_id"`)}
	}
	if v, ok := _c.mutation.AuthenticatorID(); ok {
		if err := passwordauthenticator.AuthenticatorIDValidator(v); err != nil {
			return &ValidationError{Name: "authenticator_id", err: fmt.Errorf(`ent: validator failed for field "PasswordAuthenticator.authenticator_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "PasswordAuthenticator.password_hash"`)}
	}
	if v, ok := _c.mutation.PasswordHash(); ok {
		if err := passwordauthenticator.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "PasswordAuthenticator.password_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChangedTime(); !ok {
		return &ValidationError{Name: "changed_time", err: errors.New(`ent: missing required field "PasswordAuthenticator.changed_time"`)}
	}
	return nil
}

func (_c *PasswordAuthenticatorCreate) sqlSave(ctx context.Context) (*PasswordAuthenticator, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PasswordAuthenticator.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PasswordAuthenticatorCreate) createSpec() (*PasswordAuthenticator, *sqlgraph.CreateSpec) {
	var (
		_node = &PasswordAuthenticator{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(passwordauthenticator.Table, sqlgraph.NewFieldSpec(passwordauthenticator.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AuthenticatorID(); ok {
		_spec.SetField(passwordauthenticator.FieldAuthenticatorID, field.TypeString, value)
		_node.AuthenticatorID = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(passwordauthenticator.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.ChangedTime(); ok {
		_spec.SetField(passwordauthenticator.FieldChangedTime, field.TypeTime, value)
		_node.ChangedTime = value
	}
	return _node, _spec
}

// PasswordAuthenticatorCreateBulk is the builder for creating many PasswordAuthenticator entities in bulk.
type PasswordAuthenticatorCreateBulk struct {
	config
	err      error
	builders []*PasswordAuthenticatorCreate
}

// Save creates the PasswordAuthenticator entities in the database.
func (_c *PasswordAuthenticatorCreateBulk) Save(ctx context.Context) ([]*PasswordAuthenticator, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PasswordAuthenticator, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PasswordAuthenticatorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PasswordAuthenticatorCreateBulk) SaveX(ctx context.Context) []*PasswordAuthenticator {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasswordAuthenticatorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasswordAuthenticatorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
