// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/authenticator"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/emailverificationtoken"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/iamloginsession"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/loginidentifier"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oauthaccesstoken"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oauthauthorizationcode"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oauthclient"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oauthrefreshtoken"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oauthtokensession"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oidcauthorizationrequest"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/oidcsigningkey"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/passwordauthenticator"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/passwordresettoken"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/user"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authenticatorFields := schema.Authenticator{}.Fields()
	_ = authenticatorFields
	// authenticatorDescUserID is the schema descriptor for user_id field.
	authenticatorDescUserID := authenticatorFields[1].Descriptor()
	// authenticator.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	authenticator.UserIDValidator = authenticatorDescUserID.Validators[0].(func(string) error)
	// authenticatorDescType is the schema descriptor for type field.
	authenticatorDescType := authenticatorFields[2].Descriptor()
	// authenticator.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	authenticator.TypeValidator = authenticatorDescType.Validators[0].(func(string) error)
	// authenticatorDescState is the schema descriptor for state field.
	authenticatorDescState := authenticatorFields[3].Descriptor()
	// authenticator.DefaultState holds the default value on creation for the state field.
	authenticator.DefaultState = authenticatorDescState.Default.(string)
	// authenticatorDescCreateTime is the schema descriptor for create_time field.
	authenticatorDescCreateTime := authenticatorFields[8].Descriptor()
	// authenticator.DefaultCreateTime holds the default value on creation for the create_time field.
	authenticator.DefaultCreateTime = authenticatorDescCreateTime.Default.(func() time.Time)
	// authenticatorDescUpdateTime is the schema descriptor for update_time field.
	authenticatorDescUpdateTime := authenticatorFields[9].Descriptor()
	// authenticator.DefaultUpdateTime holds the default value on creation for the update_time field.
	authenticator.DefaultUpdateTime = authenticatorDescUpdateTime.Default.(func() time.Time)
	// authenticator.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	authenticator.UpdateDefaultUpdateTime = authenticatorDescUpdateTime.UpdateDefault.(func() time.Time)
	emailverificationtokenFields := schema.EmailVerificationToken{}.Fields()
	_ = emailverificationtokenFields
	// emailverificationtokenDescUserID is the schema descriptor for user_id field.
	emailverificationtokenDescUserID := emailverificationtokenFields[1].Descriptor()
	// emailverificationtoken.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	emailverificationtoken.UserIDValidator = emailverificationtokenDescUserID.Validators[0].(func(string) error)
	// emailverificationtokenDescLoginIdentifierID is the schema descriptor for login_identifier_id field.
	emailverificationtokenDescLoginIdentifierID := emailverificationtokenFields[2].Descriptor()
	// emailverificationtoken.LoginIdentifierIDValidator is a validator for the "login_identifier_id" field. It is called by the builders before save.
	emailverificationtoken.LoginIdentifierIDValidator = emailverificationtokenDescLoginIdentifierID.Validators[0].(func(string) error)
	// emailverificationtokenDescTokenHash is the schema descriptor for token_hash field.
	emailverificationtokenDescTokenHash := emailverificationtokenFields[3].Descriptor()
	// emailverificationtoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	emailverificationtoken.TokenHashValidator = emailverificationtokenDescTokenHash.Validators[0].(func(string) error)
	// emailverificationtokenDescCreateTime is the schema descriptor for create_time field.
	emailverificationtokenDescCreateTime := emailverificationtokenFields[6].Descriptor()
	// emailverificationtoken.DefaultCreateTime holds the default value on creation for the create_time field.
	emailverificationtoken.DefaultCreateTime = emailverificationtokenDescCreateTime.Default.(func() time.Time)
	iamloginsessionFields := schema.IAMLoginSession{}.Fields()
	_ = iamloginsessionFields
	// iamloginsessionDescUserID is the schema descriptor for user_id field.
	iamloginsessionDescUserID := iamloginsessionFields[1].Descriptor()
	// iamloginsession.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	iamloginsession.UserIDValidator = iamloginsessionDescUserID.Validators[0].(func(string) error)
	// iamloginsessionDescSecretHash is the schema descriptor for secret_hash field.
	iamloginsessionDescSecretHash := iamloginsessionFields[2].Descriptor()
	// iamloginsession.SecretHashValidator is a validator for the "secret_hash" field. It is called by the builders before save.
	iamloginsession.SecretHashValidator = iamloginsessionDescSecretHash.Validators[0].(func(string) error)
	// iamloginsessionDescCreateTime is the schema descriptor for create_time field.
	iamloginsessionDescCreateTime := iamloginsessionFields[3].Descriptor()
	// iamloginsession.DefaultCreateTime holds the default value on creation for the create_time field.
	iamloginsession.DefaultCreateTime = iamloginsessionDescCreateTime.Default.(func() time.Time)
	// iamloginsessionDescLastSeenTime is the schema descriptor for last_seen_time field.
	iamloginsessionDescLastSeenTime := iamloginsessionFields[4].Descriptor()
	// iamloginsession.DefaultLastSeenTime holds the default value on creation for the last_seen_time field.
	iamloginsession.DefaultLastSeenTime = iamloginsessionDescLastSeenTime.Default.(func() time.Time)
	loginidentifierFields := schema.LoginIdentifier{}.Fields()
	_ = loginidentifierFields
	// loginidentifierDescUserID is the schema descriptor for user_id field.
	loginidentifierDescUserID := loginidentifierFields[1].Descriptor()
	// loginidentifier.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	loginidentifier.UserIDValidator = loginidentifierDescUserID.Validators[0].(func(string) error)
	// loginidentifierDescType is the schema descriptor for type field.
	loginidentifierDescType := loginidentifierFields[2].Descriptor()
	// loginidentifier.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	loginidentifier.TypeValidator = loginidentifierDescType.Validators[0].(func(string) error)
	// loginidentifierDescCanonicalValue is the schema descriptor for canonical_value field.
	loginidentifierDescCanonicalValue := loginidentifierFields[3].Descriptor()
	// loginidentifier.CanonicalValueValidator is a validator for the "canonical_value" field. It is called by the builders before save.
	loginidentifier.CanonicalValueValidator = loginidentifierDescCanonicalValue.Validators[0].(func(string) error)
	// loginidentifierDescDisplayValue is the schema descriptor for display_value field.
	loginidentifierDescDisplayValue := loginidentifierFields[4].Descriptor()
	// loginidentifier.DisplayValueValidator is a validator for the "display_value" field. It is called by the builders before save.
	loginidentifier.DisplayValueValidator = loginidentifierDescDisplayValue.Validators[0].(func(string) error)
	// loginidentifierDescCreateTime is the schema descriptor for create_time field.
	loginidentifierDescCreateTime := loginidentifierFields[6].Descriptor()
	// loginidentifier.DefaultCreateTime holds the default value on creation for the create_time field.
	loginidentifier.DefaultCreateTime = loginidentifierDescCreateTime.Default.(func() time.Time)
	// loginidentifierDescUpdateTime is the schema descriptor for update_time field.
	loginidentifierDescUpdateTime := loginidentifierFields[7].Descriptor()
	// loginidentifier.DefaultUpdateTime holds the default value on creation for the update_time field.
	loginidentifier.DefaultUpdateTime = loginidentifierDescUpdateTime.Default.(func() time.Time)
	// loginidentifier.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	loginidentifier.UpdateDefaultUpdateTime = loginidentifierDescUpdateTime.UpdateDefault.(func() time.Time)
	oauthaccesstokenFields := schema.OAuthAccessToken{}.Fields()
	_ = oauthaccesstokenFields
	// oauthaccesstokenDescTokenSessionID is the schema descriptor for token_session_id field.
	oauthaccesstokenDescTokenSessionID := oauthaccesstokenFields[1].Descriptor()
	// oauthaccesstoken.TokenSessionIDValidator is a validator for the "token_session_id" field. It is called by the builders before save.
	oauthaccesstoken.TokenSessionIDValidator = oauthaccesstokenDescTokenSessionID.Validators[0].(func(string) error)
	// oauthaccesstokenDescSubject is the schema descriptor for subject field.
	oauthaccesstokenDescSubject := oauthaccesstokenFields[2].Descriptor()
	// oauthaccesstoken.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	oauthaccesstoken.SubjectValidator = oauthaccesstokenDescSubject.Validators[0].(func(string) error)
	// oauthaccesstokenDescClientID is the schema descriptor for client_id field.
	oauthaccesstokenDescClientID := oauthaccesstokenFields[3].Descriptor()
	// oauthaccesstoken.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthaccesstoken.ClientIDValidator = oauthaccesstokenDescClientID.Validators[0].(func(string) error)
	// oauthaccesstokenDescIssuedTime is the schema descriptor for issued_time field.
	oauthaccesstokenDescIssuedTime := oauthaccesstokenFields[5].Descriptor()
	// oauthaccesstoken.DefaultIssuedTime holds the default value on creation for the issued_time field.
	oauthaccesstoken.DefaultIssuedTime = oauthaccesstokenDescIssuedTime.Default.(func() time.Time)
	oauthauthorizationcodeFields := schema.OAuthAuthorizationCode{}.Fields()
	_ = oauthauthorizationcodeFields
	// oauthauthorizationcodeDescCodeHash is the schema descriptor for code_hash field.
	oauthauthorizationcodeDescCodeHash := oauthauthorizationcodeFields[1].Descriptor()
	// oauthauthorizationcode.CodeHashValidator is a validator for the "code_hash" field. It is called by the builders before save.
	oauthauthorizationcode.CodeHashValidator = oauthauthorizationcodeDescCodeHash.Validators[0].(func(string) error)
	// oauthauthorizationcodeDescAuthorizationRequestID is the schema descriptor for authorization_request_id field.
	oauthauthorizationcodeDescAuthorizationRequestID := oauthauthorizationcodeFields[2].Descriptor()
	// oauthauthorizationcode.AuthorizationRequestIDValidator is a validator for the "authorization_request_id" field. It is called by the builders before save.
	oauthauthorizationcode.AuthorizationRequestIDValidator = oauthauthorizationcodeDescAuthorizationRequestID.Validators[0].(func(string) error)
	// oauthauthorizationcodeDescClientID is the schema descriptor for client_id field.
	oauthauthorizationcodeDescClientID := oauthauthorizationcodeFields[4].Descriptor()
	// oauthauthorizationcode.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthauthorizationcode.ClientIDValidator = oauthauthorizationcodeDescClientID.Validators[0].(func(string) error)
	// oauthauthorizationcodeDescSubject is the schema descriptor for subject field.
	oauthauthorizationcodeDescSubject := oauthauthorizationcodeFields[5].Descriptor()
	// oauthauthorizationcode.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	oauthauthorizationcode.SubjectValidator = oauthauthorizationcodeDescSubject.Validators[0].(func(string) error)
	// oauthauthorizationcodeDescRedirectURI is the schema descriptor for redirect_uri field.
	oauthauthorizationcodeDescRedirectURI := oauthauthorizationcodeFields[6].Descriptor()
	// oauthauthorizationcode.RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	oauthauthorizationcode.RedirectURIValidator = oauthauthorizationcodeDescRedirectURI.Validators[0].(func(string) error)
	// oauthauthorizationcodeDescPkceChallenge is the schema descriptor for pkce_challenge field.
	oauthauthorizationcodeDescPkceChallenge := oauthauthorizationcodeFields[8].Descriptor()
	// oauthauthorizationcode.PkceChallengeValidator is a validator for the "pkce_challenge" field. It is called by the builders before save.
	oauthauthorizationcode.PkceChallengeValidator = oauthauthorizationcodeDescPkceChallenge.Validators[0].(func(string) error)
	// oauthauthorizationcodeDescPkceChallengeMethod is the schema descriptor for pkce_challenge_method field.
	oauthauthorizationcodeDescPkceChallengeMethod := oauthauthorizationcodeFields[9].Descriptor()
	// oauthauthorizationcode.DefaultPkceChallengeMethod holds the default value on creation for the pkce_challenge_method field.
	oauthauthorizationcode.DefaultPkceChallengeMethod = oauthauthorizationcodeDescPkceChallengeMethod.Default.(string)
	// oauthauthorizationcodeDescCreateTime is the schema descriptor for create_time field.
	oauthauthorizationcodeDescCreateTime := oauthauthorizationcodeFields[12].Descriptor()
	// oauthauthorizationcode.DefaultCreateTime holds the default value on creation for the create_time field.
	oauthauthorizationcode.DefaultCreateTime = oauthauthorizationcodeDescCreateTime.Default.(func() time.Time)
	oauthclientFields := schema.OAuthClient{}.Fields()
	_ = oauthclientFields
	// oauthclientDescSecretHash is the schema descriptor for secret_hash field.
	oauthclientDescSecretHash := oauthclientFields[1].Descriptor()
	// oauthclient.SecretHashValidator is a validator for the "secret_hash" field. It is called by the builders before save.
	oauthclient.SecretHashValidator = oauthclientDescSecretHash.Validators[0].(func(string) error)
	// oauthclientDescTrusted is the schema descriptor for trusted field.
	oauthclientDescTrusted := oauthclientFields[6].Descriptor()
	// oauthclient.DefaultTrusted holds the default value on creation for the trusted field.
	oauthclient.DefaultTrusted = oauthclientDescTrusted.Default.(bool)
	// oauthclientDescCreateTime is the schema descriptor for create_time field.
	oauthclientDescCreateTime := oauthclientFields[7].Descriptor()
	// oauthclient.DefaultCreateTime holds the default value on creation for the create_time field.
	oauthclient.DefaultCreateTime = oauthclientDescCreateTime.Default.(func() time.Time)
	// oauthclientDescUpdateTime is the schema descriptor for update_time field.
	oauthclientDescUpdateTime := oauthclientFields[8].Descriptor()
	// oauthclient.DefaultUpdateTime holds the default value on creation for the update_time field.
	oauthclient.DefaultUpdateTime = oauthclientDescUpdateTime.Default.(func() time.Time)
	// oauthclient.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	oauthclient.UpdateDefaultUpdateTime = oauthclientDescUpdateTime.UpdateDefault.(func() time.Time)
	oauthrefreshtokenFields := schema.OAuthRefreshToken{}.Fields()
	_ = oauthrefreshtokenFields
	// oauthrefreshtokenDescTokenSessionID is the schema descriptor for token_session_id field.
	oauthrefreshtokenDescTokenSessionID := oauthrefreshtokenFields[1].Descriptor()
	// oauthrefreshtoken.TokenSessionIDValidator is a validator for the "token_session_id" field. It is called by the builders before save.
	oauthrefreshtoken.TokenSessionIDValidator = oauthrefreshtokenDescTokenSessionID.Validators[0].(func(string) error)
	// oauthrefreshtokenDescFamilyID is the schema descriptor for family_id field.
	oauthrefreshtokenDescFamilyID := oauthrefreshtokenFields[2].Descriptor()
	// oauthrefreshtoken.FamilyIDValidator is a validator for the "family_id" field. It is called by the builders before save.
	oauthrefreshtoken.FamilyIDValidator = oauthrefreshtokenDescFamilyID.Validators[0].(func(string) error)
	// oauthrefreshtokenDescTokenHash is the schema descriptor for token_hash field.
	oauthrefreshtokenDescTokenHash := oauthrefreshtokenFields[3].Descriptor()
	// oauthrefreshtoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	oauthrefreshtoken.TokenHashValidator = oauthrefreshtokenDescTokenHash.Validators[0].(func(string) error)
	// oauthrefreshtokenDescIssuedTime is the schema descriptor for issued_time field.
	oauthrefreshtokenDescIssuedTime := oauthrefreshtokenFields[5].Descriptor()
	// oauthrefreshtoken.DefaultIssuedTime holds the default value on creation for the issued_time field.
	oauthrefreshtoken.DefaultIssuedTime = oauthrefreshtokenDescIssuedTime.Default.(func() time.Time)
	oauthtokensessionFields := schema.OAuthTokenSession{}.Fields()
	_ = oauthtokensessionFields
	// oauthtokensessionDescUserID is the schema descriptor for user_id field.
	oauthtokensessionDescUserID := oauthtokensessionFields[1].Descriptor()
	// oauthtokensession.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	oauthtokensession.UserIDValidator = oauthtokensessionDescUserID.Validators[0].(func(string) error)
	// oauthtokensessionDescClientID is the schema descriptor for client_id field.
	oauthtokensessionDescClientID := oauthtokensessionFields[2].Descriptor()
	// oauthtokensession.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthtokensession.ClientIDValidator = oauthtokensessionDescClientID.Validators[0].(func(string) error)
	// oauthtokensessionDescIamLoginSessionID is the schema descriptor for iam_login_session_id field.
	oauthtokensessionDescIamLoginSessionID := oauthtokensessionFields[3].Descriptor()
	// oauthtokensession.IamLoginSessionIDValidator is a validator for the "iam_login_session_id" field. It is called by the builders before save.
	oauthtokensession.IamLoginSessionIDValidator = oauthtokensessionDescIamLoginSessionID.Validators[0].(func(string) error)
	// oauthtokensessionDescRefreshFamilyID is the schema descriptor for refresh_family_id field.
	oauthtokensessionDescRefreshFamilyID := oauthtokensessionFields[4].Descriptor()
	// oauthtokensession.RefreshFamilyIDValidator is a validator for the "refresh_family_id" field. It is called by the builders before save.
	oauthtokensession.RefreshFamilyIDValidator = oauthtokensessionDescRefreshFamilyID.Validators[0].(func(string) error)
	// oauthtokensessionDescCreateTime is the schema descriptor for create_time field.
	oauthtokensessionDescCreateTime := oauthtokensessionFields[9].Descriptor()
	// oauthtokensession.DefaultCreateTime holds the default value on creation for the create_time field.
	oauthtokensession.DefaultCreateTime = oauthtokensessionDescCreateTime.Default.(func() time.Time)
	// oauthtokensessionDescUpdateTime is the schema descriptor for update_time field.
	oauthtokensessionDescUpdateTime := oauthtokensessionFields[10].Descriptor()
	// oauthtokensession.DefaultUpdateTime holds the default value on creation for the update_time field.
	oauthtokensession.DefaultUpdateTime = oauthtokensessionDescUpdateTime.Default.(func() time.Time)
	// oauthtokensession.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	oauthtokensession.UpdateDefaultUpdateTime = oauthtokensessionDescUpdateTime.UpdateDefault.(func() time.Time)
	oidcauthorizationrequestFields := schema.OIDCAuthorizationRequest{}.Fields()
	_ = oidcauthorizationrequestFields
	// oidcauthorizationrequestDescClientID is the schema descriptor for client_id field.
	oidcauthorizationrequestDescClientID := oidcauthorizationrequestFields[1].Descriptor()
	// oidcauthorizationrequest.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oidcauthorizationrequest.ClientIDValidator = oidcauthorizationrequestDescClientID.Validators[0].(func(string) error)
	// oidcauthorizationrequestDescRedirectURI is the schema descriptor for redirect_uri field.
	oidcauthorizationrequestDescRedirectURI := oidcauthorizationrequestFields[2].Descriptor()
	// oidcauthorizationrequest.RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	oidcauthorizationrequest.RedirectURIValidator = oidcauthorizationrequestDescRedirectURI.Validators[0].(func(string) error)
	// oidcauthorizationrequestDescResponseType is the schema descriptor for response_type field.
	oidcauthorizationrequestDescResponseType := oidcauthorizationrequestFields[3].Descriptor()
	// oidcauthorizationrequest.ResponseTypeValidator is a validator for the "response_type" field. It is called by the builders before save.
	oidcauthorizationrequest.ResponseTypeValidator = oidcauthorizationrequestDescResponseType.Validators[0].(func(string) error)
	// oidcauthorizationrequestDescResponseMode is the schema descriptor for response_mode field.
	oidcauthorizationrequestDescResponseMode := oidcauthorizationrequestFields[4].Descriptor()
	// oidcauthorizationrequest.DefaultResponseMode holds the default value on creation for the response_mode field.
	oidcauthorizationrequest.DefaultResponseMode = oidcauthorizationrequestDescResponseMode.Default.(string)
	// oidcauthorizationrequestDescPkceChallenge is the schema descriptor for pkce_challenge field.
	oidcauthorizationrequestDescPkceChallenge := oidcauthorizationrequestFields[8].Descriptor()
	// oidcauthorizationrequest.PkceChallengeValidator is a validator for the "pkce_challenge" field. It is called by the builders before save.
	oidcauthorizationrequest.PkceChallengeValidator = oidcauthorizationrequestDescPkceChallenge.Validators[0].(func(string) error)
	// oidcauthorizationrequestDescPkceChallengeMethod is the schema descriptor for pkce_challenge_method field.
	oidcauthorizationrequestDescPkceChallengeMethod := oidcauthorizationrequestFields[9].Descriptor()
	// oidcauthorizationrequest.DefaultPkceChallengeMethod holds the default value on creation for the pkce_challenge_method field.
	oidcauthorizationrequest.DefaultPkceChallengeMethod = oidcauthorizationrequestDescPkceChallengeMethod.Default.(string)
	// oidcauthorizationrequestDescDone is the schema descriptor for done field.
	oidcauthorizationrequestDescDone := oidcauthorizationrequestFields[13].Descriptor()
	// oidcauthorizationrequest.DefaultDone holds the default value on creation for the done field.
	oidcauthorizationrequest.DefaultDone = oidcauthorizationrequestDescDone.Default.(bool)
	// oidcauthorizationrequestDescCreateTime is the schema descriptor for create_time field.
	oidcauthorizationrequestDescCreateTime := oidcauthorizationrequestFields[15].Descriptor()
	// oidcauthorizationrequest.DefaultCreateTime holds the default value on creation for the create_time field.
	oidcauthorizationrequest.DefaultCreateTime = oidcauthorizationrequestDescCreateTime.Default.(func() time.Time)
	// oidcauthorizationrequestDescUpdateTime is the schema descriptor for update_time field.
	oidcauthorizationrequestDescUpdateTime := oidcauthorizationrequestFields[16].Descriptor()
	// oidcauthorizationrequest.DefaultUpdateTime holds the default value on creation for the update_time field.
	oidcauthorizationrequest.DefaultUpdateTime = oidcauthorizationrequestDescUpdateTime.Default.(func() time.Time)
	// oidcauthorizationrequest.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	oidcauthorizationrequest.UpdateDefaultUpdateTime = oidcauthorizationrequestDescUpdateTime.UpdateDefault.(func() time.Time)
	oidcsigningkeyFields := schema.OIDCSigningKey{}.Fields()
	_ = oidcsigningkeyFields
	// oidcsigningkeyDescPublicJwk is the schema descriptor for public_jwk field.
	oidcsigningkeyDescPublicJwk := oidcsigningkeyFields[1].Descriptor()
	// oidcsigningkey.PublicJwkValidator is a validator for the "public_jwk" field. It is called by the builders before save.
	oidcsigningkey.PublicJwkValidator = oidcsigningkeyDescPublicJwk.Validators[0].(func(string) error)
	// oidcsigningkeyDescAlgorithm is the schema descriptor for algorithm field.
	oidcsigningkeyDescAlgorithm := oidcsigningkeyFields[2].Descriptor()
	// oidcsigningkey.DefaultAlgorithm holds the default value on creation for the algorithm field.
	oidcsigningkey.DefaultAlgorithm = oidcsigningkeyDescAlgorithm.Default.(string)
	// oidcsigningkeyDescCreateTime is the schema descriptor for create_time field.
	oidcsigningkeyDescCreateTime := oidcsigningkeyFields[6].Descriptor()
	// oidcsigningkey.DefaultCreateTime holds the default value on creation for the create_time field.
	oidcsigningkey.DefaultCreateTime = oidcsigningkeyDescCreateTime.Default.(func() time.Time)
	passwordauthenticatorFields := schema.PasswordAuthenticator{}.Fields()
	_ = passwordauthenticatorFields
	// passwordauthenticatorDescAuthenticatorID is the schema descriptor for authenticator_id field.
	passwordauthenticatorDescAuthenticatorID := passwordauthenticatorFields[1].Descriptor()
	// passwordauthenticator.AuthenticatorIDValidator is a validator for the "authenticator_id" field. It is called by the builders before save.
	passwordauthenticator.AuthenticatorIDValidator = passwordauthenticatorDescAuthenticatorID.Validators[0].(func(string) error)
	// passwordauthenticatorDescPasswordHash is the schema descriptor for password_hash field.
	passwordauthenticatorDescPasswordHash := passwordauthenticatorFields[2].Descriptor()
	// passwordauthenticator.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	passwordauthenticator.PasswordHashValidator = passwordauthenticatorDescPasswordHash.Validators[0].(func(string) error)
	// passwordauthenticatorDescChangedTime is the schema descriptor for changed_time field.
	passwordauthenticatorDescChangedTime := passwordauthenticatorFields[3].Descriptor()
	// passwordauthenticator.DefaultChangedTime holds the default value on creation for the changed_time field.
	passwordauthenticator.DefaultChangedTime = passwordauthenticatorDescChangedTime.Default.(func() time.Time)
	passwordresettokenFields := schema.PasswordResetToken{}.Fields()
	_ = passwordresettokenFields
	// passwordresettokenDescUserID is the schema descriptor for user_id field.
	passwordresettokenDescUserID := passwordresettokenFields[1].Descriptor()
	// passwordresettoken.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	passwordresettoken.UserIDValidator = passwordresettokenDescUserID.Validators[0].(func(string) error)
	// passwordresettokenDescTokenHash is the schema descriptor for token_hash field.
	passwordresettokenDescTokenHash := passwordresettokenFields[2].Descriptor()
	// passwordresettoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	passwordresettoken.TokenHashValidator = passwordresettokenDescTokenHash.Validators[0].(func(string) error)
	// passwordresettokenDescCreateTime is the schema descriptor for create_time field.
	passwordresettokenDescCreateTime := passwordresettokenFields[5].Descriptor()
	// passwordresettoken.DefaultCreateTime holds the default value on creation for the create_time field.
	passwordresettoken.DefaultCreateTime = passwordresettokenDescCreateTime.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[1].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescEtag is the schema descriptor for etag field.
	userDescEtag := userFields[9].Descriptor()
	// user.EtagValidator is a validator for the "etag" field. It is called by the builders before save.
	user.EtagValidator = userDescEtag.Validators[0].(func(string) error)
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userFields[10].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userFields[11].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
}
