import "../../../just/service.just"

SERVORA_EXAMPLE_SQLITE_DSN := env("SERVORA_EXAMPLE_SQLITE_DSN", "")

[unix]
test-integration:
    @{{ if SERVORA_EXAMPLE_SQLITE_DSN == "" { error("SERVORA_EXAMPLE_SQLITE_DSN is required") } else { "GOWORK=off go test -tags=integration ./internal/service -run '^TestUserReferenceIntegration$' -count=1" } }}

[windows]
test-integration:
    @{{ if SERVORA_EXAMPLE_SQLITE_DSN == "" { error("SERVORA_EXAMPLE_SQLITE_DSN is required") } else { "$env:GOWORK = \"off\"; go test -tags=integration ./internal/service -run '^TestUserReferenceIntegration$' -count=1" } }}
