// Command protoc-gen-servora-authn translates Platform AuthN annotations into
// authn_rules.gen.go files consumed by Platform AuthN runtime.
package main

import (
	"fmt"
	"path"

	authnpb "github.com/Servora-Kit/servora-platform/api/gen/go/platform/security/authn/v1"
	"github.com/Servora-Kit/servora-platform/internal/codegen/ruleplan"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		return generate(gen)
	})
}

func generate(gen *protogen.Plugin) error {
	groups, err := ruleplan.Build(gen, ruleplan.Config[*authnpb.AuthnRule]{
		MethodExtension:  authnpb.E_Rule,
		ServiceExtension: authnpb.E_ServiceDefault,
		ValidateDeclared: func(context ruleplan.DeclarationContext, rule *authnpb.AuthnRule) error {
			method := "<service_default>"
			if context.Method != nil {
				method = string(context.Method.Desc.Name())
			}
			return validateRule(
				context.File.Desc.Path(),
				string(context.Service.Desc.FullName()),
				method,
				rule,
			)
		},
	})
	if err != nil {
		return err
	}
	for _, group := range groups {
		file := group.TargetFile
		generated := gen.NewGeneratedFile(
			path.Join(group.Directory, "authn_rules.gen.go"),
			file.GoImportPath,
		)
		writeFile(generated, file.GoPackageName, group.Entries)
	}
	return nil
}

func validateRule(file, service, method string, rule *authnpb.AuthnRule) error {
	if rule == nil {
		return nil
	}
	switch mode := rule.GetMode(); mode {
	case authnpb.AuthnMode_AUTHN_MODE_UNSPECIFIED,
		authnpb.AuthnMode_AUTHN_MODE_PUBLIC,
		authnpb.AuthnMode_AUTHN_MODE_REQUIRED:
		return nil
	default:
		return fmt.Errorf("%s: service %s method %s: unknown AuthnMode %d", file, service, method, mode)
	}
}

func writeFile(g *protogen.GeneratedFile, packageName protogen.GoPackageName, rules []ruleplan.Entry[*authnpb.AuthnRule]) {
	authnPackage := protogen.GoImportPath("github.com/Servora-Kit/servora-platform/api/gen/go/platform/security/authn/v1")
	protoPackage := protogen.GoImportPath("google.golang.org/protobuf/proto")

	g.P("// Code generated by protoc-gen-servora-authn. DO NOT EDIT.")
	g.P()
	g.P("package ", packageName)
	g.P()

	ruleIdent := g.QualifiedGoIdent(protogen.GoIdent{GoName: "AuthnRule", GoImportPath: authnPackage})
	protoClone := g.QualifiedGoIdent(protogen.GoIdent{GoName: "Clone", GoImportPath: protoPackage})

	g.P("// _authnRules is the immutable backing store for AuthnRules.")
	g.P("var _authnRules = map[string]*", ruleIdent, "{")
	for _, entry := range rules {
		rule := entry.Rule
		modeIdent := g.QualifiedGoIdent(protogen.GoIdent{
			GoName:       "AuthnMode_" + rule.GetMode().String(),
			GoImportPath: authnPackage,
		})
		g.P(fmt.Sprintf("\t%q: {", entry.Operation))
		g.P("\t\tMode: ", modeIdent, ",")
		g.P("\t},")
	}
	g.P("}")
	g.P()

	g.P("// AuthnRules returns the authentication rules declared via Platform AuthN annotations.")
	g.P("// Each call returns a fresh map and cloned rule messages.")
	g.P("func AuthnRules() map[string]*", ruleIdent, " {")
	g.P("\tm := make(map[string]*", ruleIdent, ", len(_authnRules))")
	g.P("\tfor k, v := range _authnRules {")
	g.P("\t\tm[k] = ", protoClone, "(v).(*", ruleIdent, ")")
	g.P("\t}")
	g.P("\treturn m")
	g.P("}")
}
