// Code generated by ent, DO NOT EDIT.

package oauthaccesstoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the oauthaccesstoken type in the database.
	Label = "oauth_access_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTokenSessionID holds the string denoting the token_session_id field in the database.
	FieldTokenSessionID = "token_session_id"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldIssuedTime holds the string denoting the issued_time field in the database.
	FieldIssuedTime = "issued_time"
	// FieldExpiresTime holds the string denoting the expires_time field in the database.
	FieldExpiresTime = "expires_time"
	// FieldRevokedTime holds the string denoting the revoked_time field in the database.
	FieldRevokedTime = "revoked_time"
	// Table holds the table name of the oauthaccesstoken in the database.
	Table = "oauth_access_tokens"
)

// Columns holds all SQL columns for oauthaccesstoken fields.
var Columns = []string{
	FieldID,
	FieldTokenSessionID,
	FieldSubject,
	FieldClientID,
	FieldScopes,
	FieldIssuedTime,
	FieldExpiresTime,
	FieldRevokedTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TokenSessionIDValidator is a validator for the "token_session_id" field. It is called by the builders before save.
	TokenSessionIDValidator func(string) error
	// SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	SubjectValidator func(string) error
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// DefaultIssuedTime holds the default value on creation for the "issued_time" field.
	DefaultIssuedTime func() time.Time
)

// OrderOption defines the ordering options for the OAuthAccessToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTokenSessionID orders the results by the token_session_id field.
func ByTokenSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenSessionID, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByIssuedTime orders the results by the issued_time field.
func ByIssuedTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedTime, opts...).ToFunc()
}

// ByExpiresTime orders the results by the expires_time field.
func ByExpiresTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresTime, opts...).ToFunc()
}

// ByRevokedTime orders the results by the revoked_time field.
func ByRevokedTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedTime, opts...).ToFunc()
}
