syntax = "proto3";

package platform.infra.openfga.v1;

import "servora/conf/v1/annotations.proto";

option go_package = "github.com/Servora-Kit/servora-platform/api/gen/go/platform/infra/openfga/v1;openfgaconfpb";

// OpenFGA configures the Platform OpenFGA SDK client.
message OpenFGA {
  option (servora.conf.v1.section) = {
    key: "openfga"
    optional: true
  };

  string api_url = 1 [(servora.conf.v1.field) = {required: true}];
  string store_id = 2 [(servora.conf.v1.field) = {required: true}];
  string model_id = 3;
  string api_token = 4;
}
