// Code generated by ent, DO NOT EDIT.

package passwordauthenticator

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the passwordauthenticator type in the database.
	Label = "password_authenticator"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAuthenticatorID holds the string denoting the authenticator_id field in the database.
	FieldAuthenticatorID = "authenticator_id"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldChangedTime holds the string denoting the changed_time field in the database.
	FieldChangedTime = "changed_time"
	// Table holds the table name of the passwordauthenticator in the database.
	Table = "password_authenticators"
)

// Columns holds all SQL columns for passwordauthenticator fields.
var Columns = []string{
	FieldID,
	FieldAuthenticatorID,
	FieldPasswordHash,
	FieldChangedTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AuthenticatorIDValidator is a validator for the "authenticator_id" field. It is called by the builders before save.
	AuthenticatorIDValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// DefaultChangedTime holds the default value on creation for the "changed_time" field.
	DefaultChangedTime func() time.Time
)

// OrderOption defines the ordering options for the PasswordAuthenticator queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAuthenticatorID orders the results by the authenticator_id field.
func ByAuthenticatorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthenticatorID, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByChangedTime orders the results by the changed_time field.
func ByChangedTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedTime, opts...).ToFunc()
}
