// Code generated by ent, DO NOT EDIT.

package oidcsigningkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldContainsFold(FieldID, id))
}

// PublicJwk applies equality check predicate on the "public_jwk" field. It's identical to PublicJwkEQ.
func PublicJwk(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldPublicJwk, v))
}

// Algorithm applies equality check predicate on the "algorithm" field. It's identical to AlgorithmEQ.
func Algorithm(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldAlgorithm, v))
}

// NotBeforeTime applies equality check predicate on the "not_before_time" field. It's identical to NotBeforeTimeEQ.
func NotBeforeTime(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldNotBeforeTime, v))
}

// ExpiresTime applies equality check predicate on the "expires_time" field. It's identical to ExpiresTimeEQ.
func ExpiresTime(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldExpiresTime, v))
}

// RevokedTime applies equality check predicate on the "revoked_time" field. It's identical to RevokedTimeEQ.
func RevokedTime(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldRevokedTime, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldCreateTime, v))
}

// PublicJwkEQ applies the EQ predicate on the "public_jwk" field.
func PublicJwkEQ(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldPublicJwk, v))
}

// PublicJwkNEQ applies the NEQ predicate on the "public_jwk" field.
func PublicJwkNEQ(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNEQ(FieldPublicJwk, v))
}

// PublicJwkIn applies the In predicate on the "public_jwk" field.
func PublicJwkIn(vs ...string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldIn(FieldPublicJwk, vs...))
}

// PublicJwkNotIn applies the NotIn predicate on the "public_jwk" field.
func PublicJwkNotIn(vs ...string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNotIn(FieldPublicJwk, vs...))
}

// PublicJwkGT applies the GT predicate on the "public_jwk" field.
func PublicJwkGT(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGT(FieldPublicJwk, v))
}

// PublicJwkGTE applies the GTE predicate on the "public_jwk" field.
func PublicJwkGTE(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGTE(FieldPublicJwk, v))
}

// PublicJwkLT applies the LT predicate on the "public_jwk" field.
func PublicJwkLT(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLT(FieldPublicJwk, v))
}

// PublicJwkLTE applies the LTE predicate on the "public_jwk" field.
func PublicJwkLTE(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLTE(FieldPublicJwk, v))
}

// PublicJwkContains applies the Contains predicate on the "public_jwk" field.
func PublicJwkContains(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldContains(FieldPublicJwk, v))
}

// PublicJwkHasPrefix applies the HasPrefix predicate on the "public_jwk" field.
func PublicJwkHasPrefix(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldHasPrefix(FieldPublicJwk, v))
}

// PublicJwkHasSuffix applies the HasSuffix predicate on the "public_jwk" field.
func PublicJwkHasSuffix(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldHasSuffix(FieldPublicJwk, v))
}

// PublicJwkEqualFold applies the EqualFold predicate on the "public_jwk" field.
func PublicJwkEqualFold(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEqualFold(FieldPublicJwk, v))
}

// PublicJwkContainsFold applies the ContainsFold predicate on the "public_jwk" field.
func PublicJwkContainsFold(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldContainsFold(FieldPublicJwk, v))
}

// AlgorithmEQ applies the EQ predicate on the "algorithm" field.
func AlgorithmEQ(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldAlgorithm, v))
}

// AlgorithmNEQ applies the NEQ predicate on the "algorithm" field.
func AlgorithmNEQ(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNEQ(FieldAlgorithm, v))
}

// AlgorithmIn applies the In predicate on the "algorithm" field.
func AlgorithmIn(vs ...string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldIn(FieldAlgorithm, vs...))
}

// AlgorithmNotIn applies the NotIn predicate on the "algorithm" field.
func AlgorithmNotIn(vs ...string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNotIn(FieldAlgorithm, vs...))
}

// AlgorithmGT applies the GT predicate on the "algorithm" field.
func AlgorithmGT(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGT(FieldAlgorithm, v))
}

// AlgorithmGTE applies the GTE predicate on the "algorithm" field.
func AlgorithmGTE(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGTE(FieldAlgorithm, v))
}

// AlgorithmLT applies the LT predicate on the "algorithm" field.
func AlgorithmLT(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLT(FieldAlgorithm, v))
}

// AlgorithmLTE applies the LTE predicate on the "algorithm" field.
func AlgorithmLTE(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLTE(FieldAlgorithm, v))
}

// AlgorithmContains applies the Contains predicate on the "algorithm" field.
func AlgorithmContains(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldContains(FieldAlgorithm, v))
}

// AlgorithmHasPrefix applies the HasPrefix predicate on the "algorithm" field.
func AlgorithmHasPrefix(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldHasPrefix(FieldAlgorithm, v))
}

// AlgorithmHasSuffix applies the HasSuffix predicate on the "algorithm" field.
func AlgorithmHasSuffix(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldHasSuffix(FieldAlgorithm, v))
}

// AlgorithmEqualFold applies the EqualFold predicate on the "algorithm" field.
func AlgorithmEqualFold(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEqualFold(FieldAlgorithm, v))
}

// AlgorithmContainsFold applies the ContainsFold predicate on the "algorithm" field.
func AlgorithmContainsFold(v string) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldContainsFold(FieldAlgorithm, v))
}

// NotBeforeTimeEQ applies the EQ predicate on the "not_before_time" field.
func NotBeforeTimeEQ(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldNotBeforeTime, v))
}

// NotBeforeTimeNEQ applies the NEQ predicate on the "not_before_time" field.
func NotBeforeTimeNEQ(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNEQ(FieldNotBeforeTime, v))
}

// NotBeforeTimeIn applies the In predicate on the "not_before_time" field.
func NotBeforeTimeIn(vs ...time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldIn(FieldNotBeforeTime, vs...))
}

// NotBeforeTimeNotIn applies the NotIn predicate on the "not_before_time" field.
func NotBeforeTimeNotIn(vs ...time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNotIn(FieldNotBeforeTime, vs...))
}

// NotBeforeTimeGT applies the GT predicate on the "not_before_time" field.
func NotBeforeTimeGT(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGT(FieldNotBeforeTime, v))
}

// NotBeforeTimeGTE applies the GTE predicate on the "not_before_time" field.
func NotBeforeTimeGTE(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGTE(FieldNotBeforeTime, v))
}

// NotBeforeTimeLT applies the LT predicate on the "not_before_time" field.
func NotBeforeTimeLT(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLT(FieldNotBeforeTime, v))
}

// NotBeforeTimeLTE applies the LTE predicate on the "not_before_time" field.
func NotBeforeTimeLTE(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLTE(FieldNotBeforeTime, v))
}

// ExpiresTimeEQ applies the EQ predicate on the "expires_time" field.
func ExpiresTimeEQ(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldExpiresTime, v))
}

// ExpiresTimeNEQ applies the NEQ predicate on the "expires_time" field.
func ExpiresTimeNEQ(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNEQ(FieldExpiresTime, v))
}

// ExpiresTimeIn applies the In predicate on the "expires_time" field.
func ExpiresTimeIn(vs ...time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldIn(FieldExpiresTime, vs...))
}

// ExpiresTimeNotIn applies the NotIn predicate on the "expires_time" field.
func ExpiresTimeNotIn(vs ...time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNotIn(FieldExpiresTime, vs...))
}

// ExpiresTimeGT applies the GT predicate on the "expires_time" field.
func ExpiresTimeGT(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGT(FieldExpiresTime, v))
}

// ExpiresTimeGTE applies the GTE predicate on the "expires_time" field.
func ExpiresTimeGTE(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGTE(FieldExpiresTime, v))
}

// ExpiresTimeLT applies the LT predicate on the "expires_time" field.
func ExpiresTimeLT(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLT(FieldExpiresTime, v))
}

// ExpiresTimeLTE applies the LTE predicate on the "expires_time" field.
func ExpiresTimeLTE(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLTE(FieldExpiresTime, v))
}

// RevokedTimeEQ applies the EQ predicate on the "revoked_time" field.
func RevokedTimeEQ(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldRevokedTime, v))
}

// RevokedTimeNEQ applies the NEQ predicate on the "revoked_time" field.
func RevokedTimeNEQ(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNEQ(FieldRevokedTime, v))
}

// RevokedTimeIn applies the In predicate on the "revoked_time" field.
func RevokedTimeIn(vs ...time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldIn(FieldRevokedTime, vs...))
}

// RevokedTimeNotIn applies the NotIn predicate on the "revoked_time" field.
func RevokedTimeNotIn(vs ...time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNotIn(FieldRevokedTime, vs...))
}

// RevokedTimeGT applies the GT predicate on the "revoked_time" field.
func RevokedTimeGT(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGT(FieldRevokedTime, v))
}

// RevokedTimeGTE applies the GTE predicate on the "revoked_time" field.
func RevokedTimeGTE(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGTE(FieldRevokedTime, v))
}

// RevokedTimeLT applies the LT predicate on the "revoked_time" field.
func RevokedTimeLT(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLT(FieldRevokedTime, v))
}

// RevokedTimeLTE applies the LTE predicate on the "revoked_time" field.
func RevokedTimeLTE(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLTE(FieldRevokedTime, v))
}

// RevokedTimeIsNil applies the IsNil predicate on the "revoked_time" field.
func RevokedTimeIsNil() predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldIsNull(FieldRevokedTime))
}

// RevokedTimeNotNil applies the NotNil predicate on the "revoked_time" field.
func RevokedTimeNotNil() predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNotNull(FieldRevokedTime))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.FieldLTE(FieldCreateTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OIDCSigningKey) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OIDCSigningKey) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OIDCSigningKey) predicate.OIDCSigningKey {
	return predicate.OIDCSigningKey(sql.NotPredicates(p))
}
