// Code generated by ent, DO NOT EDIT.

package oidcauthorizationrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the oidcauthorizationrequest type in the database.
	Label = "oidc_authorization_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldRedirectURI holds the string denoting the redirect_uri field in the database.
	FieldRedirectURI = "redirect_uri"
	// FieldResponseType holds the string denoting the response_type field in the database.
	FieldResponseType = "response_type"
	// FieldResponseMode holds the string denoting the response_mode field in the database.
	FieldResponseMode = "response_mode"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldNonce holds the string denoting the nonce field in the database.
	FieldNonce = "nonce"
	// FieldPkceChallenge holds the string denoting the pkce_challenge field in the database.
	FieldPkceChallenge = "pkce_challenge"
	// FieldPkceChallengeMethod holds the string denoting the pkce_challenge_method field in the database.
	FieldPkceChallengeMethod = "pkce_challenge_method"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldIamLoginSessionID holds the string denoting the iam_login_session_id field in the database.
	FieldIamLoginSessionID = "iam_login_session_id"
	// FieldAuthTime holds the string denoting the auth_time field in the database.
	FieldAuthTime = "auth_time"
	// FieldDone holds the string denoting the done field in the database.
	FieldDone = "done"
	// FieldExpiresTime holds the string denoting the expires_time field in the database.
	FieldExpiresTime = "expires_time"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// Table holds the table name of the oidcauthorizationrequest in the database.
	Table = "oidc_authorization_requests"
)

// Columns holds all SQL columns for oidcauthorizationrequest fields.
var Columns = []string{
	FieldID,
	FieldClientID,
	FieldRedirectURI,
	FieldResponseType,
	FieldResponseMode,
	FieldScopes,
	FieldState,
	FieldNonce,
	FieldPkceChallenge,
	FieldPkceChallengeMethod,
	FieldSubject,
	FieldIamLoginSessionID,
	FieldAuthTime,
	FieldDone,
	FieldExpiresTime,
	FieldCreateTime,
	FieldUpdateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	RedirectURIValidator func(string) error
	// ResponseTypeValidator is a validator for the "response_type" field. It is called by the builders before save.
	ResponseTypeValidator func(string) error
	// DefaultResponseMode holds the default value on creation for the "response_mode" field.
	DefaultResponseMode string
	// PkceChallengeValidator is a validator for the "pkce_challenge" field. It is called by the builders before save.
	PkceChallengeValidator func(string) error
	// DefaultPkceChallengeMethod holds the default value on creation for the "pkce_challenge_method" field.
	DefaultPkceChallengeMethod string
	// DefaultDone holds the default value on creation for the "done" field.
	DefaultDone bool
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)

// OrderOption defines the ordering options for the OIDCAuthorizationRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByRedirectURI orders the results by the redirect_uri field.
func ByRedirectURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedirectURI, opts...).ToFunc()
}

// ByResponseType orders the results by the response_type field.
func ByResponseType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseType, opts...).ToFunc()
}

// ByResponseMode orders the results by the response_mode field.
func ByResponseMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseMode, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByNonce orders the results by the nonce field.
func ByNonce(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNonce, opts...).ToFunc()
}

// ByPkceChallenge orders the results by the pkce_challenge field.
func ByPkceChallenge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPkceChallenge, opts...).ToFunc()
}

// ByPkceChallengeMethod orders the results by the pkce_challenge_method field.
func ByPkceChallengeMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPkceChallengeMethod, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByIamLoginSessionID orders the results by the iam_login_session_id field.
func ByIamLoginSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIamLoginSessionID, opts...).ToFunc()
}

// ByAuthTime orders the results by the auth_time field.
func ByAuthTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthTime, opts...).ToFunc()
}

// ByDone orders the results by the done field.
func ByDone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDone, opts...).ToFunc()
}

// ByExpiresTime orders the results by the expires_time field.
func ByExpiresTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresTime, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}
