// Code generated by ent, DO NOT EDIT.

package oidcauthorizationrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContainsFold(FieldID, id))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldClientID, v))
}

// RedirectURI applies equality check predicate on the "redirect_uri" field. It's identical to RedirectURIEQ.
func RedirectURI(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldRedirectURI, v))
}

// ResponseType applies equality check predicate on the "response_type" field. It's identical to ResponseTypeEQ.
func ResponseType(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldResponseType, v))
}

// ResponseMode applies equality check predicate on the "response_mode" field. It's identical to ResponseModeEQ.
func ResponseMode(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldResponseMode, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldState, v))
}

// Nonce applies equality check predicate on the "nonce" field. It's identical to NonceEQ.
func Nonce(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldNonce, v))
}

// PkceChallenge applies equality check predicate on the "pkce_challenge" field. It's identical to PkceChallengeEQ.
func PkceChallenge(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldPkceChallenge, v))
}

// PkceChallengeMethod applies equality check predicate on the "pkce_challenge_method" field. It's identical to PkceChallengeMethodEQ.
func PkceChallengeMethod(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldPkceChallengeMethod, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldSubject, v))
}

// IamLoginSessionID applies equality check predicate on the "iam_login_session_id" field. It's identical to IamLoginSessionIDEQ.
func IamLoginSessionID(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldIamLoginSessionID, v))
}

// AuthTime applies equality check predicate on the "auth_time" field. It's identical to AuthTimeEQ.
func AuthTime(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldAuthTime, v))
}

// Done applies equality check predicate on the "done" field. It's identical to DoneEQ.
func Done(v bool) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldDone, v))
}

// ExpiresTime applies equality check predicate on the "expires_time" field. It's identical to ExpiresTimeEQ.
func ExpiresTime(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldExpiresTime, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldUpdateTime, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContainsFold(FieldClientID, v))
}

// RedirectURIEQ applies the EQ predicate on the "redirect_uri" field.
func RedirectURIEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldRedirectURI, v))
}

// RedirectURINEQ applies the NEQ predicate on the "redirect_uri" field.
func RedirectURINEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldRedirectURI, v))
}

// RedirectURIIn applies the In predicate on the "redirect_uri" field.
func RedirectURIIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldRedirectURI, vs...))
}

// RedirectURINotIn applies the NotIn predicate on the "redirect_uri" field.
func RedirectURINotIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldRedirectURI, vs...))
}

// RedirectURIGT applies the GT predicate on the "redirect_uri" field.
func RedirectURIGT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldRedirectURI, v))
}

// RedirectURIGTE applies the GTE predicate on the "redirect_uri" field.
func RedirectURIGTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldRedirectURI, v))
}

// RedirectURILT applies the LT predicate on the "redirect_uri" field.
func RedirectURILT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldRedirectURI, v))
}

// RedirectURILTE applies the LTE predicate on the "redirect_uri" field.
func RedirectURILTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldRedirectURI, v))
}

// RedirectURIContains applies the Contains predicate on the "redirect_uri" field.
func RedirectURIContains(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContains(FieldRedirectURI, v))
}

// RedirectURIHasPrefix applies the HasPrefix predicate on the "redirect_uri" field.
func RedirectURIHasPrefix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasPrefix(FieldRedirectURI, v))
}

// RedirectURIHasSuffix applies the HasSuffix predicate on the "redirect_uri" field.
func RedirectURIHasSuffix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasSuffix(FieldRedirectURI, v))
}

// RedirectURIEqualFold applies the EqualFold predicate on the "redirect_uri" field.
func RedirectURIEqualFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEqualFold(FieldRedirectURI, v))
}

// RedirectURIContainsFold applies the ContainsFold predicate on the "redirect_uri" field.
func RedirectURIContainsFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContainsFold(FieldRedirectURI, v))
}

// ResponseTypeEQ applies the EQ predicate on the "response_type" field.
func ResponseTypeEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldResponseType, v))
}

// ResponseTypeNEQ applies the NEQ predicate on the "response_type" field.
func ResponseTypeNEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldResponseType, v))
}

// ResponseTypeIn applies the In predicate on the "response_type" field.
func ResponseTypeIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldResponseType, vs...))
}

// ResponseTypeNotIn applies the NotIn predicate on the "response_type" field.
func ResponseTypeNotIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldResponseType, vs...))
}

// ResponseTypeGT applies the GT predicate on the "response_type" field.
func ResponseTypeGT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldResponseType, v))
}

// ResponseTypeGTE applies the GTE predicate on the "response_type" field.
func ResponseTypeGTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldResponseType, v))
}

// ResponseTypeLT applies the LT predicate on the "response_type" field.
func ResponseTypeLT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldResponseType, v))
}

// ResponseTypeLTE applies the LTE predicate on the "response_type" field.
func ResponseTypeLTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldResponseType, v))
}

// ResponseTypeContains applies the Contains predicate on the "response_type" field.
func ResponseTypeContains(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContains(FieldResponseType, v))
}

// ResponseTypeHasPrefix applies the HasPrefix predicate on the "response_type" field.
func ResponseTypeHasPrefix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasPrefix(FieldResponseType, v))
}

// ResponseTypeHasSuffix applies the HasSuffix predicate on the "response_type" field.
func ResponseTypeHasSuffix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasSuffix(FieldResponseType, v))
}

// ResponseTypeEqualFold applies the EqualFold predicate on the "response_type" field.
func ResponseTypeEqualFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEqualFold(FieldResponseType, v))
}

// ResponseTypeContainsFold applies the ContainsFold predicate on the "response_type" field.
func ResponseTypeContainsFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContainsFold(FieldResponseType, v))
}

// ResponseModeEQ applies the EQ predicate on the "response_mode" field.
func ResponseModeEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldResponseMode, v))
}

// ResponseModeNEQ applies the NEQ predicate on the "response_mode" field.
func ResponseModeNEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldResponseMode, v))
}

// ResponseModeIn applies the In predicate on the "response_mode" field.
func ResponseModeIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldResponseMode, vs...))
}

// ResponseModeNotIn applies the NotIn predicate on the "response_mode" field.
func ResponseModeNotIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldResponseMode, vs...))
}

// ResponseModeGT applies the GT predicate on the "response_mode" field.
func ResponseModeGT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldResponseMode, v))
}

// ResponseModeGTE applies the GTE predicate on the "response_mode" field.
func ResponseModeGTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldResponseMode, v))
}

// ResponseModeLT applies the LT predicate on the "response_mode" field.
func ResponseModeLT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldResponseMode, v))
}

// ResponseModeLTE applies the LTE predicate on the "response_mode" field.
func ResponseModeLTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldResponseMode, v))
}

// ResponseModeContains applies the Contains predicate on the "response_mode" field.
func ResponseModeContains(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContains(FieldResponseMode, v))
}

// ResponseModeHasPrefix applies the HasPrefix predicate on the "response_mode" field.
func ResponseModeHasPrefix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasPrefix(FieldResponseMode, v))
}

// ResponseModeHasSuffix applies the HasSuffix predicate on the "response_mode" field.
func ResponseModeHasSuffix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasSuffix(FieldResponseMode, v))
}

// ResponseModeIsNil applies the IsNil predicate on the "response_mode" field.
func ResponseModeIsNil() predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIsNull(FieldResponseMode))
}

// ResponseModeNotNil applies the NotNil predicate on the "response_mode" field.
func ResponseModeNotNil() predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotNull(FieldResponseMode))
}

// ResponseModeEqualFold applies the EqualFold predicate on the "response_mode" field.
func ResponseModeEqualFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEqualFold(FieldResponseMode, v))
}

// ResponseModeContainsFold applies the ContainsFold predicate on the "response_mode" field.
func ResponseModeContainsFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContainsFold(FieldResponseMode, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasSuffix(FieldState, v))
}

// StateIsNil applies the IsNil predicate on the "state" field.
func StateIsNil() predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIsNull(FieldState))
}

// StateNotNil applies the NotNil predicate on the "state" field.
func StateNotNil() predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotNull(FieldState))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContainsFold(FieldState, v))
}

// NonceEQ applies the EQ predicate on the "nonce" field.
func NonceEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldNonce, v))
}

// NonceNEQ applies the NEQ predicate on the "nonce" field.
func NonceNEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldNonce, v))
}

// NonceIn applies the In predicate on the "nonce" field.
func NonceIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldNonce, vs...))
}

// NonceNotIn applies the NotIn predicate on the "nonce" field.
func NonceNotIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldNonce, vs...))
}

// NonceGT applies the GT predicate on the "nonce" field.
func NonceGT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldNonce, v))
}

// NonceGTE applies the GTE predicate on the "nonce" field.
func NonceGTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldNonce, v))
}

// NonceLT applies the LT predicate on the "nonce" field.
func NonceLT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldNonce, v))
}

// NonceLTE applies the LTE predicate on the "nonce" field.
func NonceLTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldNonce, v))
}

// NonceContains applies the Contains predicate on the "nonce" field.
func NonceContains(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContains(FieldNonce, v))
}

// NonceHasPrefix applies the HasPrefix predicate on the "nonce" field.
func NonceHasPrefix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasPrefix(FieldNonce, v))
}

// NonceHasSuffix applies the HasSuffix predicate on the "nonce" field.
func NonceHasSuffix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasSuffix(FieldNonce, v))
}

// NonceIsNil applies the IsNil predicate on the "nonce" field.
func NonceIsNil() predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIsNull(FieldNonce))
}

// NonceNotNil applies the NotNil predicate on the "nonce" field.
func NonceNotNil() predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotNull(FieldNonce))
}

// NonceEqualFold applies the EqualFold predicate on the "nonce" field.
func NonceEqualFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEqualFold(FieldNonce, v))
}

// NonceContainsFold applies the ContainsFold predicate on the "nonce" field.
func NonceContainsFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContainsFold(FieldNonce, v))
}

// PkceChallengeEQ applies the EQ predicate on the "pkce_challenge" field.
func PkceChallengeEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldPkceChallenge, v))
}

// PkceChallengeNEQ applies the NEQ predicate on the "pkce_challenge" field.
func PkceChallengeNEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldPkceChallenge, v))
}

// PkceChallengeIn applies the In predicate on the "pkce_challenge" field.
func PkceChallengeIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldPkceChallenge, vs...))
}

// PkceChallengeNotIn applies the NotIn predicate on the "pkce_challenge" field.
func PkceChallengeNotIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldPkceChallenge, vs...))
}

// PkceChallengeGT applies the GT predicate on the "pkce_challenge" field.
func PkceChallengeGT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldPkceChallenge, v))
}

// PkceChallengeGTE applies the GTE predicate on the "pkce_challenge" field.
func PkceChallengeGTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldPkceChallenge, v))
}

// PkceChallengeLT applies the LT predicate on the "pkce_challenge" field.
func PkceChallengeLT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldPkceChallenge, v))
}

// PkceChallengeLTE applies the LTE predicate on the "pkce_challenge" field.
func PkceChallengeLTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldPkceChallenge, v))
}

// PkceChallengeContains applies the Contains predicate on the "pkce_challenge" field.
func PkceChallengeContains(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContains(FieldPkceChallenge, v))
}

// PkceChallengeHasPrefix applies the HasPrefix predicate on the "pkce_challenge" field.
func PkceChallengeHasPrefix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasPrefix(FieldPkceChallenge, v))
}

// PkceChallengeHasSuffix applies the HasSuffix predicate on the "pkce_challenge" field.
func PkceChallengeHasSuffix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasSuffix(FieldPkceChallenge, v))
}

// PkceChallengeEqualFold applies the EqualFold predicate on the "pkce_challenge" field.
func PkceChallengeEqualFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEqualFold(FieldPkceChallenge, v))
}

// PkceChallengeContainsFold applies the ContainsFold predicate on the "pkce_challenge" field.
func PkceChallengeContainsFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContainsFold(FieldPkceChallenge, v))
}

// PkceChallengeMethodEQ applies the EQ predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldPkceChallengeMethod, v))
}

// PkceChallengeMethodNEQ applies the NEQ predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodNEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldPkceChallengeMethod, v))
}

// PkceChallengeMethodIn applies the In predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldPkceChallengeMethod, vs...))
}

// PkceChallengeMethodNotIn applies the NotIn predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodNotIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldPkceChallengeMethod, vs...))
}

// PkceChallengeMethodGT applies the GT predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodGT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldPkceChallengeMethod, v))
}

// PkceChallengeMethodGTE applies the GTE predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodGTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldPkceChallengeMethod, v))
}

// PkceChallengeMethodLT applies the LT predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodLT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldPkceChallengeMethod, v))
}

// PkceChallengeMethodLTE applies the LTE predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodLTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldPkceChallengeMethod, v))
}

// PkceChallengeMethodContains applies the Contains predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodContains(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContains(FieldPkceChallengeMethod, v))
}

// PkceChallengeMethodHasPrefix applies the HasPrefix predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodHasPrefix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasPrefix(FieldPkceChallengeMethod, v))
}

// PkceChallengeMethodHasSuffix applies the HasSuffix predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodHasSuffix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasSuffix(FieldPkceChallengeMethod, v))
}

// PkceChallengeMethodEqualFold applies the EqualFold predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodEqualFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEqualFold(FieldPkceChallengeMethod, v))
}

// PkceChallengeMethodContainsFold applies the ContainsFold predicate on the "pkce_challenge_method" field.
func PkceChallengeMethodContainsFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContainsFold(FieldPkceChallengeMethod, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectIsNil applies the IsNil predicate on the "subject" field.
func SubjectIsNil() predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIsNull(FieldSubject))
}

// SubjectNotNil applies the NotNil predicate on the "subject" field.
func SubjectNotNil() predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotNull(FieldSubject))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContainsFold(FieldSubject, v))
}

// IamLoginSessionIDEQ applies the EQ predicate on the "iam_login_session_id" field.
func IamLoginSessionIDEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldIamLoginSessionID, v))
}

// IamLoginSessionIDNEQ applies the NEQ predicate on the "iam_login_session_id" field.
func IamLoginSessionIDNEQ(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldIamLoginSessionID, v))
}

// IamLoginSessionIDIn applies the In predicate on the "iam_login_session_id" field.
func IamLoginSessionIDIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldIamLoginSessionID, vs...))
}

// IamLoginSessionIDNotIn applies the NotIn predicate on the "iam_login_session_id" field.
func IamLoginSessionIDNotIn(vs ...string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldIamLoginSessionID, vs...))
}

// IamLoginSessionIDGT applies the GT predicate on the "iam_login_session_id" field.
func IamLoginSessionIDGT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldIamLoginSessionID, v))
}

// IamLoginSessionIDGTE applies the GTE predicate on the "iam_login_session_id" field.
func IamLoginSessionIDGTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldIamLoginSessionID, v))
}

// IamLoginSessionIDLT applies the LT predicate on the "iam_login_session_id" field.
func IamLoginSessionIDLT(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldIamLoginSessionID, v))
}

// IamLoginSessionIDLTE applies the LTE predicate on the "iam_login_session_id" field.
func IamLoginSessionIDLTE(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldIamLoginSessionID, v))
}

// IamLoginSessionIDContains applies the Contains predicate on the "iam_login_session_id" field.
func IamLoginSessionIDContains(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContains(FieldIamLoginSessionID, v))
}

// IamLoginSessionIDHasPrefix applies the HasPrefix predicate on the "iam_login_session_id" field.
func IamLoginSessionIDHasPrefix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasPrefix(FieldIamLoginSessionID, v))
}

// IamLoginSessionIDHasSuffix applies the HasSuffix predicate on the "iam_login_session_id" field.
func IamLoginSessionIDHasSuffix(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldHasSuffix(FieldIamLoginSessionID, v))
}

// IamLoginSessionIDIsNil applies the IsNil predicate on the "iam_login_session_id" field.
func IamLoginSessionIDIsNil() predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIsNull(FieldIamLoginSessionID))
}

// IamLoginSessionIDNotNil applies the NotNil predicate on the "iam_login_session_id" field.
func IamLoginSessionIDNotNil() predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotNull(FieldIamLoginSessionID))
}

// IamLoginSessionIDEqualFold applies the EqualFold predicate on the "iam_login_session_id" field.
func IamLoginSessionIDEqualFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEqualFold(FieldIamLoginSessionID, v))
}

// IamLoginSessionIDContainsFold applies the ContainsFold predicate on the "iam_login_session_id" field.
func IamLoginSessionIDContainsFold(v string) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldContainsFold(FieldIamLoginSessionID, v))
}

// AuthTimeEQ applies the EQ predicate on the "auth_time" field.
func AuthTimeEQ(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldAuthTime, v))
}

// AuthTimeNEQ applies the NEQ predicate on the "auth_time" field.
func AuthTimeNEQ(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldAuthTime, v))
}

// AuthTimeIn applies the In predicate on the "auth_time" field.
func AuthTimeIn(vs ...time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldAuthTime, vs...))
}

// AuthTimeNotIn applies the NotIn predicate on the "auth_time" field.
func AuthTimeNotIn(vs ...time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldAuthTime, vs...))
}

// AuthTimeGT applies the GT predicate on the "auth_time" field.
func AuthTimeGT(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldAuthTime, v))
}

// AuthTimeGTE applies the GTE predicate on the "auth_time" field.
func AuthTimeGTE(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldAuthTime, v))
}

// AuthTimeLT applies the LT predicate on the "auth_time" field.
func AuthTimeLT(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldAuthTime, v))
}

// AuthTimeLTE applies the LTE predicate on the "auth_time" field.
func AuthTimeLTE(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldAuthTime, v))
}

// AuthTimeIsNil applies the IsNil predicate on the "auth_time" field.
func AuthTimeIsNil() predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIsNull(FieldAuthTime))
}

// AuthTimeNotNil applies the NotNil predicate on the "auth_time" field.
func AuthTimeNotNil() predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotNull(FieldAuthTime))
}

// DoneEQ applies the EQ predicate on the "done" field.
func DoneEQ(v bool) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldDone, v))
}

// DoneNEQ applies the NEQ predicate on the "done" field.
func DoneNEQ(v bool) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldDone, v))
}

// ExpiresTimeEQ applies the EQ predicate on the "expires_time" field.
func ExpiresTimeEQ(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldExpiresTime, v))
}

// ExpiresTimeNEQ applies the NEQ predicate on the "expires_time" field.
func ExpiresTimeNEQ(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldExpiresTime, v))
}

// ExpiresTimeIn applies the In predicate on the "expires_time" field.
func ExpiresTimeIn(vs ...time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldExpiresTime, vs...))
}

// ExpiresTimeNotIn applies the NotIn predicate on the "expires_time" field.
func ExpiresTimeNotIn(vs ...time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldExpiresTime, vs...))
}

// ExpiresTimeGT applies the GT predicate on the "expires_time" field.
func ExpiresTimeGT(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldExpiresTime, v))
}

// ExpiresTimeGTE applies the GTE predicate on the "expires_time" field.
func ExpiresTimeGTE(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldExpiresTime, v))
}

// ExpiresTimeLT applies the LT predicate on the "expires_time" field.
func ExpiresTimeLT(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldExpiresTime, v))
}

// ExpiresTimeLTE applies the LTE predicate on the "expires_time" field.
func ExpiresTimeLTE(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldExpiresTime, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.FieldLTE(FieldUpdateTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OIDCAuthorizationRequest) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OIDCAuthorizationRequest) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OIDCAuthorizationRequest) predicate.OIDCAuthorizationRequest {
	return predicate.OIDCAuthorizationRequest(sql.NotPredicates(p))
}
