syntax = "proto3";

package example.service.v1;

import "google/api/annotations.proto";
import "test/service/v1/test.proto";

option go_package = "github.com/Servora-Kit/plateau/api/gen/go/example/service/v1;examplepb";
option java_multiple_files = true;
option java_outer_classname = "ExampleTestProto";
option java_package = "dev.servora.example.service.v1";

service ExampleService {
  rpc Hello(test.service.v1.HelloRequest) returns (test.service.v1.HelloResponse) {
    option (google.api.http) = {get: "/v1/hello"};
  }
}
