// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Authenticator is the predicate function for authenticator builders.
type Authenticator func(*sql.Selector)

// EmailVerificationToken is the predicate function for emailverificationtoken builders.
type EmailVerificationToken func(*sql.Selector)

// IAMLoginSession is the predicate function for iamloginsession builders.
type IAMLoginSession func(*sql.Selector)

// LoginIdentifier is the predicate function for loginidentifier builders.
type LoginIdentifier func(*sql.Selector)

// OAuthAccessToken is the predicate function for oauthaccesstoken builders.
type OAuthAccessToken func(*sql.Selector)

// OAuthAuthorizationCode is the predicate function for oauthauthorizationcode builders.
type OAuthAuthorizationCode func(*sql.Selector)

// OAuthClient is the predicate function for oauthclient builders.
type OAuthClient func(*sql.Selector)

// OAuthRefreshToken is the predicate function for oauthrefreshtoken builders.
type OAuthRefreshToken func(*sql.Selector)

// OAuthTokenSession is the predicate function for oauthtokensession builders.
type OAuthTokenSession func(*sql.Selector)

// OIDCAuthorizationRequest is the predicate function for oidcauthorizationrequest builders.
type OIDCAuthorizationRequest func(*sql.Selector)

// OIDCSigningKey is the predicate function for oidcsigningkey builders.
type OIDCSigningKey func(*sql.Selector)

// PasswordAuthenticator is the predicate function for passwordauthenticator builders.
type PasswordAuthenticator func(*sql.Selector)

// PasswordResetToken is the predicate function for passwordresettoken builders.
type PasswordResetToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
