// Code generated by ent, DO NOT EDIT.

package httpsession

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the httpsession type in the database.
	Label = "http_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "token"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// FieldExpiry holds the string denoting the expiry field in the database.
	FieldExpiry = "expiry"
	// Table holds the table name of the httpsession in the database.
	Table = "sessions"
)

// Columns holds all SQL columns for httpsession fields.
var Columns = []string{
	FieldID,
	FieldData,
	FieldExpiry,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the HTTPSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByExpiry orders the results by the expiry field.
func ByExpiry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiry, opts...).ToFunc()
}
