syntax = "proto3";

package plateau.security.authn.jwt.v1;

import "plateau/security/jwt/v1/config.proto";
import "servora/conf/v1/annotations.proto";

option go_package = "github.com/Servora-Kit/plateau/api/gen/go/plateau/security/authn/jwt/v1;jwtv1";

// JwtAuthnConfig configures one Resource Server JWT verifier profile.
message JwtAuthnConfig {
  option (servora.conf.v1.section) = {
    key: "jwt"
    optional: true
  };

  string issuer = 1;
  string audience = 2;
  repeated plateau.security.jwt.v1.VerificationKey verification_keys = 3;
}
