// Code generated by ent, DO NOT EDIT.

package oauthrefreshtoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the oauthrefreshtoken type in the database.
	Label = "oauth_refresh_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTokenSessionID holds the string denoting the token_session_id field in the database.
	FieldTokenSessionID = "token_session_id"
	// FieldFamilyID holds the string denoting the family_id field in the database.
	FieldFamilyID = "family_id"
	// FieldTokenHash holds the string denoting the token_hash field in the database.
	FieldTokenHash = "token_hash"
	// FieldParentTokenID holds the string denoting the parent_token_id field in the database.
	FieldParentTokenID = "parent_token_id"
	// FieldIssuedTime holds the string denoting the issued_time field in the database.
	FieldIssuedTime = "issued_time"
	// FieldExpiresTime holds the string denoting the expires_time field in the database.
	FieldExpiresTime = "expires_time"
	// FieldConsumedTime holds the string denoting the consumed_time field in the database.
	FieldConsumedTime = "consumed_time"
	// FieldRevokedTime holds the string denoting the revoked_time field in the database.
	FieldRevokedTime = "revoked_time"
	// Table holds the table name of the oauthrefreshtoken in the database.
	Table = "oauth_refresh_tokens"
)

// Columns holds all SQL columns for oauthrefreshtoken fields.
var Columns = []string{
	FieldID,
	FieldTokenSessionID,
	FieldFamilyID,
	FieldTokenHash,
	FieldParentTokenID,
	FieldIssuedTime,
	FieldExpiresTime,
	FieldConsumedTime,
	FieldRevokedTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TokenSessionIDValidator is a validator for the "token_session_id" field. It is called by the builders before save.
	TokenSessionIDValidator func(string) error
	// FamilyIDValidator is a validator for the "family_id" field. It is called by the builders before save.
	FamilyIDValidator func(string) error
	// TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	TokenHashValidator func(string) error
	// DefaultIssuedTime holds the default value on creation for the "issued_time" field.
	DefaultIssuedTime func() time.Time
)

// OrderOption defines the ordering options for the OAuthRefreshToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTokenSessionID orders the results by the token_session_id field.
func ByTokenSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenSessionID, opts...).ToFunc()
}

// ByFamilyID orders the results by the family_id field.
func ByFamilyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFamilyID, opts...).ToFunc()
}

// ByTokenHash orders the results by the token_hash field.
func ByTokenHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenHash, opts...).ToFunc()
}

// ByParentTokenID orders the results by the parent_token_id field.
func ByParentTokenID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentTokenID, opts...).ToFunc()
}

// ByIssuedTime orders the results by the issued_time field.
func ByIssuedTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedTime, opts...).ToFunc()
}

// ByExpiresTime orders the results by the expires_time field.
func ByExpiresTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresTime, opts...).ToFunc()
}

// ByConsumedTime orders the results by the consumed_time field.
func ByConsumedTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumedTime, opts...).ToFunc()
}

// ByRevokedTime orders the results by the revoked_time field.
func ByRevokedTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedTime, opts...).ToFunc()
}
