// Code generated by ent, DO NOT EDIT.

package oauthauthorizationcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the oauthauthorizationcode type in the database.
	Label = "oauth_authorization_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCodeHash holds the string denoting the code_hash field in the database.
	FieldCodeHash = "code_hash"
	// FieldAuthorizationRequestID holds the string denoting the authorization_request_id field in the database.
	FieldAuthorizationRequestID = "authorization_request_id"
	// FieldTokenSessionID holds the string denoting the token_session_id field in the database.
	FieldTokenSessionID = "token_session_id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldRedirectURI holds the string denoting the redirect_uri field in the database.
	FieldRedirectURI = "redirect_uri"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldPkceChallenge holds the string denoting the pkce_challenge field in the database.
	FieldPkceChallenge = "pkce_challenge"
	// FieldPkceChallengeMethod holds the string denoting the pkce_challenge_method field in the database.
	FieldPkceChallengeMethod = "pkce_challenge_method"
	// FieldExpiresTime holds the string denoting the expires_time field in the database.
	FieldExpiresTime = "expires_time"
	// FieldConsumedTime holds the string denoting the consumed_time field in the database.
	FieldConsumedTime = "consumed_time"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// Table holds the table name of the oauthauthorizationcode in the database.
	Table = "oauth_authorization_codes"
)

// Columns holds all SQL columns for oauthauthorizationcode fields.
var Columns = []string{
	FieldID,
	FieldCodeHash,
	FieldAuthorizationRequestID,
	FieldTokenSessionID,
	FieldClientID,
	FieldSubject,
	FieldRedirectURI,
	FieldScopes,
	FieldPkceChallenge,
	FieldPkceChallengeMethod,
	FieldExpiresTime,
	FieldConsumedTime,
	FieldCreateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeHashValidator is a validator for the "code_hash" field. It is called by the builders before save.
	CodeHashValidator func(string) error
	// AuthorizationRequestIDValidator is a validator for the "authorization_request_id" field. It is called by the builders before save.
	AuthorizationRequestIDValidator func(string) error
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	SubjectValidator func(string) error
	// RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	RedirectURIValidator func(string) error
	// PkceChallengeValidator is a validator for the "pkce_challenge" field. It is called by the builders before save.
	PkceChallengeValidator func(string) error
	// DefaultPkceChallengeMethod holds the default value on creation for the "pkce_challenge_method" field.
	DefaultPkceChallengeMethod string
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
)

// OrderOption defines the ordering options for the OAuthAuthorizationCode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCodeHash orders the results by the code_hash field.
func ByCodeHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeHash, opts...).ToFunc()
}

// ByAuthorizationRequestID orders the results by the authorization_request_id field.
func ByAuthorizationRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorizationRequestID, opts...).ToFunc()
}

// ByTokenSessionID orders the results by the token_session_id field.
func ByTokenSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenSessionID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByRedirectURI orders the results by the redirect_uri field.
func ByRedirectURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedirectURI, opts...).ToFunc()
}

// ByPkceChallenge orders the results by the pkce_challenge field.
func ByPkceChallenge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPkceChallenge, opts...).ToFunc()
}

// ByPkceChallengeMethod orders the results by the pkce_challenge_method field.
func ByPkceChallengeMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPkceChallengeMethod, opts...).ToFunc()
}

// ByExpiresTime orders the results by the expires_time field.
func ByExpiresTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresTime, opts...).ToFunc()
}

// ByConsumedTime orders the results by the consumed_time field.
func ByConsumedTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumedTime, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}
