import "../../../just/settings.just"

COMPONENT_DIR := module_directory()
PNPM := env("PNPM", "pnpm")

env:
    @echo "COMPONENT_DIR: {{ COMPONENT_DIR }}"
    @echo "PNPM: {{ PNPM }}"

run: dev

[unix]
[working-directory(COMPONENT_DIR)]
dev:
    @"{{ PNPM }}" run dev

[windows]
[working-directory(COMPONENT_DIR)]
dev:
    @& "{{ PNPM }}" run dev

[unix]
[working-directory(COMPONENT_DIR)]
build:
    @"{{ PNPM }}" run build

[windows]
[working-directory(COMPONENT_DIR)]
build:
    @& "{{ PNPM }}" run build

[unix]
[working-directory(COMPONENT_DIR)]
start:
    @"{{ PNPM }}" run start

[windows]
[working-directory(COMPONENT_DIR)]
start:
    @& "{{ PNPM }}" run start

[unix]
[working-directory(COMPONENT_DIR)]
lint:
    @"{{ PNPM }}" run lint

[windows]
[working-directory(COMPONENT_DIR)]
lint:
    @& "{{ PNPM }}" run lint

_build: build

[unix]
_clean-files:
    rm -rf -- "{{ join(COMPONENT_DIR, ".next") }}"

[windows]
_clean-files:
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "{{ join(COMPONENT_DIR, ".next") }}"

clean: _clean-files
