import "../../../just/settings.just"

COMPONENT_DIR := module_directory()
PNPM := env("PNPM", "pnpm")

[unix]
[working-directory(COMPONENT_DIR)]
dev:
    @"{{ PNPM }}" run dev

[windows]
[working-directory(COMPONENT_DIR)]
dev:
    @& "{{ PNPM }}" run dev

[unix]
[working-directory(COMPONENT_DIR)]
build:
    @"{{ PNPM }}" run build

[windows]
[working-directory(COMPONENT_DIR)]
build:
    @& "{{ PNPM }}" run build

[unix]
[working-directory(COMPONENT_DIR)]
lint:
    @"{{ PNPM }}" run lint

[windows]
[working-directory(COMPONENT_DIR)]
lint:
    @& "{{ PNPM }}" run lint
